export const loanTypeDummyData = [
  {
    code: "PERSONAL_LOAN",
    name: "Personal Loan",
    description: "Unsecured loan for personal expenses",

    category: "PERSONAL_LOAN",
    secured: false,

    minAmount: 50000,
    maxAmount: 1000000,
    minTenureMonths: 12,
    maxTenureMonths: 60,

    interestType: "REDUCING",
    minInterestRate: 10,
    maxInterestRate: 24,
    defaultInterestRate: 14,

    processingFeeType: "PERCENTAGE",
    processingFee: 2,
    gstApplicable: true,
    gstPercentage: 18,

    minAge: 21,
    maxAge: 60,
    minIncome: 20000,
    employmentType: "salaried",

    minCibilScore: 650,
    maxCibilScore: 900,

    maxLoanToValueRatio: 0,

    prepaymentAllowed: true,
    foreclosureAllowed: true,
    prepaymentCharges: 2,
    foreclosureCharges: 3,

    isActive: true,
    isPublic: true,
    approvalRequired: true,

    estimatedProcessingTimeDays: 3,
    documentsRequired: "PAN, Aadhaar, Salary Slip, Bank Statement",
  },

  {
    code: "HOME_LOAN",
    name: "Home Loan",
    description: "Loan for purchasing residential property",

    category: "HOME_LOAN",
    secured: true,

    minAmount: 500000,
    maxAmount: 10000000,
    minTenureMonths: 60,
    maxTenureMonths: 360,

    interestType: "REDUCING",
    minInterestRate: 7,
    maxInterestRate: 12,
    defaultInterestRate: 8.5,

    processingFeeType: "PERCENTAGE",
    processingFee: 1,
    gstApplicable: true,
    gstPercentage: 18,

    minAge: 23,
    maxAge: 65,
    minIncome: 30000,
    employmentType: "salaried",

    minCibilScore: 700,
    maxCibilScore: 900,

    maxLoanToValueRatio: 80,

    prepaymentAllowed: true,
    foreclosureAllowed: true,
    prepaymentCharges: 0,
    foreclosureCharges: 2,

    isActive: true,
    isPublic: true,
    approvalRequired: true,

    estimatedProcessingTimeDays: 7,
    documentsRequired: "PAN, Aadhaar, Income Proof, Property Papers",
  },

  {
    code: "CAR_LOAN",
    name: "Car Loan",
    description: "Loan for purchasing a new or used car",

    category: "CAR_LOAN",
    secured: true,

    minAmount: 100000,
    maxAmount: 1500000,
    minTenureMonths: 12,
    maxTenureMonths: 84,

    interestType: "REDUCING",
    minInterestRate: 8,
    maxInterestRate: 14,
    defaultInterestRate: 10,

    processingFeeType: "PERCENTAGE",
    processingFee: 1.5,
    gstApplicable: true,
    gstPercentage: 18,

    minAge: 21,
    maxAge: 60,
    minIncome: 25000,
    employmentType: "salaried",

    minCibilScore: 680,
    maxCibilScore: 900,

    maxLoanToValueRatio: 90,

    prepaymentAllowed: true,
    foreclosureAllowed: true,
    prepaymentCharges: 2,
    foreclosureCharges: 2,

    isActive: true,
    isPublic: true,
    approvalRequired: true,

    estimatedProcessingTimeDays: 2,
    documentsRequired: "PAN, Aadhaar, Salary Slip, Car Invoice",
  },

  {
    code: "BUSINESS_LOAN",
    name: "Business Loan",
    description: "Loan for business expansion and working capital",

    category: "BUSINESS_LOAN",
    secured: false,

    minAmount: 100000,
    maxAmount: 5000000,
    minTenureMonths: 12,
    maxTenureMonths: 120,

    interestType: "REDUCING",
    minInterestRate: 11,
    maxInterestRate: 22,
    defaultInterestRate: 15,

    processingFeeType: "PERCENTAGE",
    processingFee: 2,
    gstApplicable: true,
    gstPercentage: 18,

    minAge: 23,
    maxAge: 65,
    minIncome: 50000,
    employmentType: "business",

    minCibilScore: 680,
    maxCibilScore: 900,

    maxLoanToValueRatio: 75,

    prepaymentAllowed: true,
    foreclosureAllowed: true,
    prepaymentCharges: 3,
    foreclosureCharges: 4,

    isActive: true,
    isPublic: true,
    approvalRequired: true,

    estimatedProcessingTimeDays: 5,
    documentsRequired: "PAN, GST Certificate, ITR, Bank Statement",
  },
];

export const leadDummyData = [
  {
    leadNumber: "LD0001",
    fullName: "Rahul Sharma",
    contactNumber: "9876543210",
    email: "rahul.sharma@gmail.com",
    dob: "1992-05-12",
    gender: "MALE",

    loanAmount: 300000,
    loanTypeId: "cm123loan001",

    city: "Jaipur",
    state: "Rajasthan",
    pinCode: "302001",
    address: "Vaishali Nagar, Jaipur",

    assignedTo: "cm_user_101",
    assignedBy: "cm_admin_001",
    status: "INTERESTED",
  },

  {
    leadNumber: "LD0002",
    fullName: "Priya Singh",
    contactNumber: "9988776655",
    email: "priya.singh@gmail.com",
    dob: "1995-11-02",
    gender: "FEMALE",

    loanAmount: 500000,
    loanTypeId: "cm123loan002",

    city: "Delhi",
    state: "Delhi",
    pinCode: "110001",
    address: "Dwarka Sector 10",

    assignedTo: "cm_user_102",
    assignedBy: "cm_admin_001",
    status: "APPLICATION_IN_PROGRESS",
  },

  {
    leadNumber: "LD0003",
    fullName: "Amit Verma",
    contactNumber: "9123456789",
    email: "amit.verma@gmail.com",
    dob: "1989-03-20",
    gender: "MALE",

    loanAmount: 1200000,
    loanTypeId: "cm123loan003",

    city: "Mumbai",
    state: "Maharashtra",
    pinCode: "400001",
    address: "Andheri West",

    assignedTo: "cm_user_103",
    assignedBy: "cm_admin_001",
    status: "UNDER_REVIEW",
  },

  {
    leadNumber: "LD0004",
    fullName: "Sneha Patel",
    contactNumber: "9012345678",
    email: "sneha.patel@gmail.com",
    dob: "1993-07-15",
    gender: "FEMALE",

    loanAmount: 800000,
    loanTypeId: "cm123loan004",

    city: "Ahmedabad",
    state: "Gujarat",
    pinCode: "380001",
    address: "Navrangpura",

    assignedTo: "cm_user_104",
    assignedBy: "cm_admin_001",
    status: "APPROVED",
  },

  {
    leadNumber: "LD0005",
    fullName: "Mohit Gupta",
    contactNumber: "9098765432",
    email: "mohit.gupta@gmail.com",
    dob: "1990-09-10",
    gender: "MALE",

    loanAmount: 250000,
    loanTypeId: "cm123loan005",

    city: "Lucknow",
    state: "Uttar Pradesh",
    pinCode: "226001",
    address: "Gomti Nagar",

    assignedTo: null,
    assignedBy: null,
    status: "PENDING",
  },
];

export const loanApplications = [
  {
    id: 1,
    loanNumber: "LN1001",
    status: "APPROVED",
    applicationDate: "2026-03-12",
    updatedAt: "2026-03-13",
    createdAt: "2026-03-12",
    branchId: "BR001",
    customer: {
      firstName: "Sohail",
      lastName: "Ahmed",
      email: "sohail@gmail.com",
      contactNumber: "9876543210",
      alternateNumber: "9876500000",
      dob: "1990-01-01",
      gender: "MALE",
      maritalStatus: "SINGLE",
      nationality: "Indian",
      category: "General",
      spouseName: "",
      address: "123 Main St",
      city: "Mumbai",
      state: "Maharashtra",
      pinCode: "400001",
      aadhaarNumber: "123412341234",
      panNumber: "ABCDE1234F",
      voterId: "VOTER1234",
      passportNumber: "P1234567",
      employmentType: "SALARIED",
      monthlyIncome: 50000,
      annualIncome: 600000,
      otherIncome: 0,
      bankName: "SBI",
      bankAccountNumber: "1234567890",
      ifscCode: "SBIN0001234",
      accountType: "SAVINGS",
    },
    requestedAmount: 500000,
    approvedAmount: 500000,
    tenureMonths: 120,
    interestRate: 8.5,
    cibilScore: 780,
    loanTypeId: "HOME_LOAN",
    interestType: "REDUCING",
    loanPurpose: "Home Purchase",
    purposeDetails: "Buying a new house",
    emiAmount: 6000,
    totalPayable: 720000,
    foreclosureAllowed: true,
    prepaymentAllowed: true,
    latePaymentFee: 500,
    bounceCharges: 350,
    foreclosureCharges: 2,
    prepaymentCharges: 1,
    coapplicants: [],
    kyc: {
      status: "VERIFIED",
      verifiedBy: "Admin",
      verifiedAt: "2026-03-12",
      documents: [
        { documentType: "Aadhaar", verificationStatus: "verified" },
        { documentType: "PAN", verificationStatus: "verified" },
      ],
    },
  },
  {
    id: 2,
    loanNumber: "LN1002",
    status: "APPROVED",
    applicationDate: "2026-03-10",
    updatedAt: "2026-03-11",
    createdAt: "2026-03-10",
    branchId: "BR002",
    customer: {
      firstName: "Ali",
      lastName: "Khan",
      email: "ali@gmail.com",
      contactNumber: "9123456789",
      alternateNumber: "9123400000",
      dob: "1988-05-15",
      gender: "MALE",
      maritalStatus: "MARRIED",
      nationality: "Indian",
      category: "OBC",
      spouseName: "Ayesha Khan",
      address: "456 Park Ave",
      city: "Delhi",
      state: "Delhi",
      pinCode: "110001",
      aadhaarNumber: "234523452345",
      panNumber: "FGHIJ5678K",
      voterId: "VOTER5678",
      passportNumber: "P7654321",
      employmentType: "SALARIED",
      monthlyIncome: 40000,
      annualIncome: 480000,
      otherIncome: 5000,
      bankName: "HDFC",
      bankAccountNumber: "2345678901",
      ifscCode: "HDFC0002345",
      accountType: "SAVINGS",
    },
    requestedAmount: 300000,
    approvedAmount: 300000,
    tenureMonths: 60,
    interestRate: 10.0,
    cibilScore: 720,
    loanTypeId: "CAR_LOAN",
    interestType: "REDUCING",
    loanPurpose: "Car Purchase",
    purposeDetails: "Buying a new car",
    emiAmount: 6500,
    totalPayable: 390000,
    foreclosureAllowed: true,
    prepaymentAllowed: true,
    latePaymentFee: 400,
    bounceCharges: 250,
    foreclosureCharges: 2,
    prepaymentCharges: 1,
    coapplicants: [],
    kyc: {
      status: "VERIFIED",
      verifiedBy: "Admin",
      verifiedAt: "2026-03-10",
      documents: [
        { documentType: "Aadhaar", verificationStatus: "verified" },
        { documentType: "PAN", verificationStatus: "verified" },
      ],
    },
  },
  {
    id: 3,
    loanNumber: "LN1003",
    status: "APPROVED",
    applicationDate: "2026-03-08",
    updatedAt: "2026-03-09",
    createdAt: "2026-03-08",
    branchId: "BR003",
    customer: {
      firstName: "Rahul",
      lastName: "Sharma",
      email: "rahul@gmail.com",
      contactNumber: "9988776655",
      alternateNumber: "9988700000",
      dob: "1992-05-12",
      gender: "MALE",
      maritalStatus: "SINGLE",
      nationality: "Indian",
      category: "General",
      spouseName: "",
      address: "789 Lake Rd",
      city: "Bangalore",
      state: "Karnataka",
      pinCode: "560001",
      aadhaarNumber: "345634563456",
      panNumber: "KLMNO9012P",
      voterId: "VOTER9012",
      passportNumber: "P2345678",
      employmentType: "SALARIED",
      monthlyIncome: 35000,
      annualIncome: 420000,
      otherIncome: 2000,
      bankName: "ICICI",
      bankAccountNumber: "3456789012",
      ifscCode: "ICIC0003456",
      accountType: "SAVINGS",
    },
    requestedAmount: 200000,
    approvedAmount: 200000,
    tenureMonths: 36,
    interestRate: 12.0,
    cibilScore: 690,
    loanTypeId: "PERSONAL_LOAN",
    interestType: "REDUCING",
    loanPurpose: "Personal Expenses",
    purposeDetails: "Medical and travel",
    emiAmount: 7000,
    totalPayable: 252000,
    foreclosureAllowed: true,
    prepaymentAllowed: true,
    latePaymentFee: 300,
    bounceCharges: 150,
    foreclosureCharges: 2,
    prepaymentCharges: 1,
    coapplicants: [],
    kyc: {
      status: "VERIFIED",
      verifiedBy: "Admin",
      verifiedAt: "2026-03-08",
      documents: [
        { documentType: "Aadhaar", verificationStatus: "verified" },
        { documentType: "PAN", verificationStatus: "verified" },
      ],
    },
  },
];
