export const APPLICATION_FORM_INITIAL_DATA = {
  name: "",
  email: "",
  phone: "",
  income: "",
  address: "",
  aadhaar: "",
  pan: "",
  cibil: "",
  amount: "",
  tenure: "12",
  interest: "10.5",
  occupation: "",
  loanType: "Personal Loan",
};

export const SAMPLE_LOAN_APPLICATIONS = [
  {
    id: 1,
    customer: {
      firstName: "Rajesh",
      lastName: "Kumar",
      email: "rajesh.kumar@email.com",
      contactNumber: "+91 98765 43210",
      panNumber: "ABCDE1234F",
      aadhaarNumber: "1234 5678 9012",
      address: "123, MG Road, Bangalore, Karnataka - 560001",
      occupation: "Software Engineer",
      monthlyIncome: "850000",
    },
    requestedAmount: "500000",
    tenureMonths: "24",
    interestRate: "10.5",
    cibilScore: 780,
    loanType: "Personal Loan",
    status: "APPROVED",
    appliedDate: "2026-03-01",
    approvedDate: "2026-03-05",
  },
  {
    id: 2,
    customer: {
      firstName: "Priya",
      lastName: "Sharma",
      email: "priya.sharma@email.com",
      contactNumber: "+91 87654 32109",
      panNumber: "FGHIJ5678K",
      aadhaarNumber: "2345 6789 0123",
      address: "45/B, Park Street, Mumbai, Maharashtra - 400001",
      occupation: "Marketing Manager",
      monthlyIncome: "650000",
    },
    requestedAmount: "300000",
    tenureMonths: "12",
    interestRate: "11.0",
    cibilScore: 725,
    loanType: "Personal Loan",
    status: "PENDING",
    appliedDate: "2026-03-08",
  },
  {
    id: 3,
    customer: {
      firstName: "Amit",
      lastName: "Patel",
      email: "amit.patel@email.com",
      contactNumber: "+91 76543 21098",
      panNumber: "KLMNO9012P",
      aadhaarNumber: "3456 7890 1234",
      address: "78, CG Road, Ahmedabad, Gujarat - 380009",
      occupation: "Business Owner",
      monthlyIncome: "1200000",
    },
    requestedAmount: "750000",
    tenureMonths: "36",
    interestRate: "9.5",
    cibilScore: 810,
    loanType: "Business Loan",
    status: "UNDER_REVIEW",
    appliedDate: "2026-03-05",
  },
  {
    id: 4,
    customer: {
      firstName: "Sneha",
      lastName: "Desai",
      email: "sneha.desai@email.com",
      contactNumber: "+91 65432 10987",
      panNumber: "PQRST3456U",
      aadhaarNumber: "4567 8901 2345",
      address: "12, Anna Salai, Chennai, Tamil Nadu - 600002",
      occupation: "Teacher",
      monthlyIncome: "450000",
    },
    requestedAmount: "200000",
    tenureMonths: "18",
    interestRate: "12.0",
    cibilScore: 690,
    loanType: "Personal Loan",
    status: "REJECTED",
    appliedDate: "2026-02-28",
    rejectedDate: "2026-03-02",
    rejectionReason: "Insufficient income",
  },
  {
    id: 5,
    customer: {
      firstName: "Vikram",
      lastName: "Singh",
      email: "vikram.singh@email.com",
      contactNumber: "+91 54321 09876",
      panNumber: "UVWXY7890Z",
      aadhaarNumber: "5678 9012 3456",
      address: "89/C, Connaught Place, New Delhi, Delhi - 110001",
      occupation: "Financial Analyst",
      monthlyIncome: "950000",
    },
    requestedAmount: "600000",
    tenureMonths: "24",
    interestRate: "10.0",
    cibilScore: 755,
    loanType: "Personal Loan",
    status: "APPROVED",
    appliedDate: "2026-02-25",
    approvedDate: "2026-03-01",
  },

  {
    id: 6,
    customer: {
      firstName: "Arjun",
      lastName: "Mehta",
      email: "arjun.mehta@email.com",
      contactNumber: "+91 91234 56789",
      panNumber: "ABCDE6789L",
      aadhaarNumber: "6789 1234 5678",
      address: "12, Banjara Hills, Hyderabad, Telangana - 500034",
      occupation: "Doctor",
      monthlyIncome: "1100000",
    },
    requestedAmount: "800000",
    tenureMonths: "36",
    interestRate: "9.2",
    cibilScore: 805,
    loanType: "Personal Loan",
    status: "APPROVED",
    appliedDate: "2026-03-02",
    approvedDate: "2026-03-06",
  },

  {
    id: 7,
    customer: {
      firstName: "Neha",
      lastName: "Gupta",
      email: "neha.gupta@email.com",
      contactNumber: "+91 90123 45678",
      panNumber: "FGHIJ1122M",
      aadhaarNumber: "7890 1234 5678",
      address: "Sector 62, Noida, Uttar Pradesh - 201309",
      occupation: "UI Designer",
      monthlyIncome: "550000",
    },
    requestedAmount: "250000",
    tenureMonths: "12",
    interestRate: "11.3",
    cibilScore: 710,
    loanType: "Personal Loan",
    status: "PENDING",
    appliedDate: "2026-03-10",
  },

  {
    id: 8,
    customer: {
      firstName: "Rahul",
      lastName: "Verma",
      email: "rahul.verma@email.com",
      contactNumber: "+91 92345 67890",
      panNumber: "KLMNO3344N",
      aadhaarNumber: "8901 2345 6789",
      address: "Salt Lake, Kolkata, West Bengal - 700091",
      occupation: "Chartered Accountant",
      monthlyIncome: "980000",
    },
    requestedAmount: "400000",
    tenureMonths: "24",
    interestRate: "10.1",
    cibilScore: 765,
    loanType: "Personal Loan",
    status: "UNDER_REVIEW",
    appliedDate: "2026-03-04",
  },

  {
    id: 9,
    customer: {
      firstName: "Kavita",
      lastName: "Joshi",
      email: "kavita.joshi@email.com",
      contactNumber: "+91 93456 78901",
      panNumber: "PQRS1234T",
      aadhaarNumber: "9012 3456 7890",
      address: "FC Road, Pune, Maharashtra - 411004",
      occupation: "Professor",
      monthlyIncome: "720000",
    },
    requestedAmount: "350000",
    tenureMonths: "18",
    interestRate: "10.8",
    cibilScore: 735,
    loanType: "Education Loan",
    status: "APPROVED",
    appliedDate: "2026-02-26",
    approvedDate: "2026-03-03",
  },

  {
    id: 10,
    customer: {
      firstName: "Rohit",
      lastName: "Bansal",
      email: "rohit.bansal@email.com",
      contactNumber: "+91 94567 89012",
      panNumber: "UVWX5678Y",
      aadhaarNumber: "1122 3344 5566",
      address: "Model Town, Ludhiana, Punjab - 141002",
      occupation: "Retailer",
      monthlyIncome: "600000",
    },
    requestedAmount: "500000",
    tenureMonths: "30",
    interestRate: "11.5",
    cibilScore: 680,
    loanType: "Business Loan",
    status: "REJECTED",
    appliedDate: "2026-02-20",
    rejectedDate: "2026-02-24",
    rejectionReason: "Low credit score",
  },

  {
    id: 11,
    customer: {
      firstName: "Anjali",
      lastName: "Kapoor",
      email: "anjali.kapoor@email.com",
      contactNumber: "+91 95678 90123",
      panNumber: "AAAAA9999A",
      aadhaarNumber: "2233 4455 6677",
      address: "Indiranagar, Bangalore, Karnataka - 560038",
      occupation: "HR Manager",
      monthlyIncome: "780000",
    },
    requestedAmount: "420000",
    tenureMonths: "24",
    interestRate: "10.4",
    cibilScore: 760,
    loanType: "Personal Loan",
    status: "APPROVED",
    appliedDate: "2026-03-01",
    approvedDate: "2026-03-06",
  },

  {
    id: 12,
    customer: {
      firstName: "Suresh",
      lastName: "Iyer",
      email: "suresh.iyer@email.com",
      contactNumber: "+91 96789 01234",
      panNumber: "BBBBB8888B",
      aadhaarNumber: "3344 5566 7788",
      address: "T Nagar, Chennai, Tamil Nadu - 600017",
      occupation: "Restaurant Owner",
      monthlyIncome: "1300000",
    },
    requestedAmount: "900000",
    tenureMonths: "48",
    interestRate: "9.0",
    cibilScore: 820,
    loanType: "Business Loan",
    status: "UNDER_REVIEW",
    appliedDate: "2026-03-07",
  },

  {
    id: 13,
    customer: {
      firstName: "Pooja",
      lastName: "Nair",
      email: "pooja.nair@email.com",
      contactNumber: "+91 97890 12345",
      panNumber: "CCCCC7777C",
      aadhaarNumber: "4455 6677 8899",
      address: "Kakkanad, Kochi, Kerala - 682030",
      occupation: "Data Scientist",
      monthlyIncome: "1020000",
    },
    requestedAmount: "550000",
    tenureMonths: "24",
    interestRate: "9.9",
    cibilScore: 790,
    loanType: "Personal Loan",
    status: "APPROVED",
    appliedDate: "2026-03-02",
    approvedDate: "2026-03-07",
  },

  {
    id: 14,
    customer: {
      firstName: "Manoj",
      lastName: "Tiwari",
      email: "manoj.tiwari@email.com",
      contactNumber: "+91 98901 23456",
      panNumber: "DDDDD6666D",
      aadhaarNumber: "5566 7788 9900",
      address: "Aliganj, Lucknow, Uttar Pradesh - 226024",
      occupation: "Government Officer",
      monthlyIncome: "680000",
    },
    requestedAmount: "300000",
    tenureMonths: "20",
    interestRate: "10.7",
    cibilScore: 745,
    loanType: "Personal Loan",
    status: "PENDING",
    appliedDate: "2026-03-11",
  },

  {
    id: 15,
    customer: {
      firstName: "Karan",
      lastName: "Malhotra",
      email: "karan.malhotra@email.com",
      contactNumber: "+91 99012 34567",
      panNumber: "EEEEE5555E",
      aadhaarNumber: "6677 8899 0011",
      address: "Karol Bagh, New Delhi - 110005",
      occupation: "Entrepreneur",
      monthlyIncome: "1500000",
    },
    requestedAmount: "1000000",
    tenureMonths: "48",
    interestRate: "8.9",
    cibilScore: 830,
    loanType: "Business Loan",
    status: "APPROVED",
    appliedDate: "2026-02-22",
    approvedDate: "2026-02-27",
  },

  {
    id: 16,
    customer: {
      firstName: "Meena",
      lastName: "Reddy",
      email: "meena.reddy@email.com",
      contactNumber: "+91 90198 76543",
      panNumber: "FFFFF4444F",
      aadhaarNumber: "7788 9900 1122",
      address: "Gachibowli, Hyderabad, Telangana - 500032",
      occupation: "Pharmacist",
      monthlyIncome: "520000",
    },
    requestedAmount: "220000",
    tenureMonths: "18",
    interestRate: "11.8",
    cibilScore: 695,
    loanType: "Personal Loan",
    status: "UNDER_REVIEW",
    appliedDate: "2026-03-09",
  },

  {
    id: 17,
    customer: {
      firstName: "Deepak",
      lastName: "Yadav",
      email: "deepak.yadav@email.com",
      contactNumber: "+91 93456 12098",
      panNumber: "GGGGG3333G",
      aadhaarNumber: "8899 0011 2233",
      address: "Vaishali Nagar, Jaipur, Rajasthan - 302021",
      occupation: "Civil Engineer",
      monthlyIncome: "870000",
    },
    requestedAmount: "470000",
    tenureMonths: "30",
    interestRate: "10.2",
    cibilScore: 770,
    loanType: "Personal Loan",
    status: "APPROVED",
    appliedDate: "2026-03-01",
    approvedDate: "2026-03-05",
  },

  {
    id: 18,
    customer: {
      firstName: "Farhan",
      lastName: "Ali",
      email: "farhan.ali@email.com",
      contactNumber: "+91 92345 56712",
      panNumber: "HHHHH2222H",
      aadhaarNumber: "9900 1122 3344",
      address: "Alkapuri, Vadodara, Gujarat - 390007",
      occupation: "Trader",
      monthlyIncome: "740000",
    },
    requestedAmount: "360000",
    tenureMonths: "24",
    interestRate: "10.9",
    cibilScore: 720,
    loanType: "Business Loan",
    status: "PENDING",
    appliedDate: "2026-03-12",
  },

  {
    id: 19,
    customer: {
      firstName: "Divya",
      lastName: "Kulkarni",
      email: "divya.k@email.com",
      contactNumber: "+91 94561 90876",
      panNumber: "IIIII1111I",
      aadhaarNumber: "1010 2020 3030",
      address: "Baner, Pune, Maharashtra - 411045",
      occupation: "Architect",
      monthlyIncome: "890000",
    },
    requestedAmount: "410000",
    tenureMonths: "24",
    interestRate: "10.0",
    cibilScore: 775,
    loanType: "Personal Loan",
    status: "UNDER_REVIEW",
    appliedDate: "2026-03-06",
  },

  {
    id: 20,
    customer: {
      firstName: "Nikhil",
      lastName: "Saxena",
      email: "nikhil.saxena@email.com",
      contactNumber: "+91 91234 89076",
      panNumber: "JJJJJ0000J",
      aadhaarNumber: "4040 5050 6060",
      address: "Indore, Madhya Pradesh - 452001",
      occupation: "Bank Manager",
      monthlyIncome: "970000",
    },
    requestedAmount: "650000",
    tenureMonths: "36",
    interestRate: "9.8",
    cibilScore: 800,
    loanType: "Personal Loan",
    status: "APPROVED",
    appliedDate: "2026-02-27",
    approvedDate: "2026-03-03",
  },
];
// Credit Check Page Data
export const CREDIT_CHECK_LOAN_APPLICATIONS = [
  {
    id: "LN-2024-1256",
    applicationNumber: "LN-2024-1256",
    loanNumber: "LON-2024-001",
    applicantName: "Rajesh Kumar",
    coApplicantName: "Priya Kumar",
    loanType: "Home Loan",
    loanAmount: 2500000,
    branchName: "Mumbai Central",
    currentStage: "Credit Check",
    monthlyIncome: 150000,
    panNumber: "ABCDE1234F",
    dob: "15-08-1985",
    mobile: "+91 9876543210",
    employmentType: "Salaried",
    companyName: "Tech Solutions Pvt Ltd",
    tenure: 20,
    interestRate: 8.5,
  },
  {
    id: "LN-2024-1257",
    applicationNumber: "LN-2024-1257",
    loanNumber: "LON-2024-002",
    applicantName: "Amit Sharma",
    coApplicantName: null,
    loanType: "Personal Loan",
    loanAmount: 500000,
    branchName: "Delhi North",
    currentStage: "Credit Check",
    monthlyIncome: 75000,
    panNumber: "EFGHI5678J",
    dob: "20-05-1990",
    mobile: "+91 9876543212",
    employmentType: "Salaried",
    companyName: "Finance Corp",
    tenure: 5,
    interestRate: 12.5,
  },
  {
    id: "LN-2024-1258",
    applicationNumber: "LN-2024-1258",
    loanNumber: "LON-2024-003",
    applicantName: "Sunita Patel",
    coApplicantName: "Rahul Patel",
    loanType: "Business Loan",
    loanAmount: 1000000,
    branchName: "Ahmedabad West",
    currentStage: "Credit Check",
    monthlyIncome: 200000,
    panNumber: "JKLMN9012O",
    dob: "12-12-1980",
    mobile: "+91 9876543213",
    employmentType: "Self-Employed",
    companyName: "Patel Traders",
    tenure: 10,
    interestRate: 10.5,
  },
];

export const CREDIT_CHECK_DATA = {
  "LON-2024-001": {
    creditScores: [
      { bureau: "CIBIL", score: 785, status: "Excellent", color: "emerald" },
      { bureau: "Experian", score: 780, status: "Excellent", color: "emerald" },
      { bureau: "Equifax", score: 765, status: "Good", color: "blue" },
      { bureau: "CRIF", score: 790, status: "Excellent", color: "emerald" },
    ],
    coApplicant: {
      name: "Priya Kumar",
      panNumber: "PQRST5678G",
      dob: "22-11-1988",
      mobile: "+91 9876543211",
      creditScore: 720,
      riskCategory: "Low Risk",
      employmentType: "Self-Employed",
      monthlyIncome: 90000,
    },
    existingLoans: [
      {
        id: 1,
        loanType: "Home Loan",
        bankName: "HDFC Bank",
        emiAmount: 25000,
        outstandingAmount: 1850000,
        overdueAmount: 0,
        status: "Active",
        statusColor: "emerald",
      },
      {
        id: 2,
        loanType: "Car Loan",
        bankName: "ICICI Bank",
        emiAmount: 12000,
        outstandingAmount: 320000,
        overdueAmount: 0,
        status: "Active",
        statusColor: "emerald",
      },
    ],
    creditAnalysis: {
      monthlyIncome: 150000,
      totalExistingEMI: 50000,
      foirPercentage: 33.33,
      eligibleEMICapacity: 75000,
      riskGrade: "B+",
      recommendedLoanAmount: 2250000,
      recommendedTenure: 20,
      interestRate: 8.5,
      creditRemarks:
        "Applicant has good credit score with manageable existing liabilities. FOIR within acceptable limits.",
    },
  },
  "LON-2024-002": {
    creditScores: [
      { bureau: "CIBIL", score: 650, status: "Fair", color: "blue" },
      { bureau: "Experian", score: 670, status: "Fair", color: "blue" },
      { bureau: "Equifax", score: 630, status: "Fair", color: "amber" },
      { bureau: "CRIF", score: 640, status: "Fair", color: "blue" },
    ],
    coApplicant: null,
    existingLoans: [
      {
        id: 1,
        loanType: "Personal Loan",
        bankName: "Axis Bank",
        emiAmount: 8000,
        outstandingAmount: 150000,
        overdueAmount: 15000,
        status: "Default",
        statusColor: "rose",
      },
    ],
    creditAnalysis: {
      monthlyIncome: 75000,
      totalExistingEMI: 8000,
      foirPercentage: 10.67,
      eligibleEMICapacity: 37500,
      riskGrade: "C",
      recommendedLoanAmount: 400000,
      recommendedTenure: 5,
      interestRate: 12.5,
      creditRemarks:
        "Applicant has average credit score with some overdue payments. Requires further verification.",
    },
  },
  "LON-2024-003": {
    creditScores: [
      { bureau: "CIBIL", score: 720, status: "Good", color: "blue" },
      { bureau: "Experian", score: 710, status: "Good", color: "blue" },
      { bureau: "Equifax", score: 730, status: "Good", color: "blue" },
      { bureau: "CRIF", score: 715, status: "Good", color: "blue" },
    ],
    coApplicant: {
      name: "Rahul Patel",
      panNumber: "STUVW3456X",
      dob: "10-03-1978",
      mobile: "+91 9876543214",
      creditScore: 680,
      riskCategory: "Medium Risk",
      employmentType: "Business",
      monthlyIncome: 120000,
    },
    existingLoans: [],
    creditAnalysis: {
      monthlyIncome: 200000,
      totalExistingEMI: 0,
      foirPercentage: 0,
      eligibleEMICapacity: 100000,
      riskGrade: "A",
      recommendedLoanAmount: 1000000,
      recommendedTenure: 10,
      interestRate: 10.5,
      creditRemarks:
        "Applicant has good credit history with no existing liabilities. Strong candidate for approval.",
    },
  },
};

export const CREDIT_CHECK_DECISIONS = {
  "LON-2024-001": {
    status: "pending",
    decisionType: "",
    recommendedAmount: 2250000,
    recommendedTenure: 20,
    interestRate: 8.5,
    riskGrade: "B+",
    remarks: "",
    officerName: "Credit Officer Sharma",
    decisionDate: new Date().toISOString().split("T")[0],
  },
  "LON-2024-002": {
    status: "pending",
    decisionType: "",
    recommendedAmount: 400000,
    recommendedTenure: 5,
    interestRate: 12.5,
    riskGrade: "C",
    remarks: "",
    officerName: "",
    decisionDate: "",
  },
  "LON-2024-003": {
    status: "pending",
    decisionType: "",
    recommendedAmount: 1000000,
    recommendedTenure: 10,
    interestRate: 10.5,
    riskGrade: "A",
    remarks: "",
    officerName: "",
    decisionDate: "",
  },
};

export const RECENT_CREDIT_SEARCHES = ["LON-2024-001", "LON-2024-002"];

// Disbursement Management Page Data
export const DISBURSEMENT_PENDING_LOANS = [
  {
    id: "LN-2024-001",
    customer: "Rajesh Kumar",
    amount: 500000,
    approvedDate: "2026-03-05",
    type: "Personal Loan",
    bank: "HDFC Bank",
    acc: "501002345678",
    ifsc: "HDFC0001234",
  },
  {
    id: "LN-2024-002",
    customer: "Priya Sharma",
    amount: 300000,
    approvedDate: "2026-03-08",
    type: "Personal Loan",
    bank: "SBI",
    acc: "30201234567",
    ifsc: "SBIN0004567",
  },
  {
    id: "LN-2024-005",
    customer: "Vikram Singh",
    amount: 600000,
    approvedDate: "2026-03-01",
    type: "Personal Loan",
    bank: "Axis Bank",
    acc: "555566667777",
    ifsc: "UTIB0001234",
  },
];

export const DISBURSEMENT_APPROVED_DVS = [
  {
    dvNo: "DV-1001",
    loanId: "LN-2024-010",
    customer: "Amit Kumar",
    amount: 400000,
    status: "approved",
    date: "2026-03-09",
    bank: "Axis Bank",
    mode: "NEFT",
    acc: "444455556666",
    ifsc: "UTIB0005678",
    type: "Business Loan",
  },
  {
    dvNo: "DV-1002",
    loanId: "LN-2024-011",
    customer: "Sneha Gupta",
    amount: 250000,
    status: "approved",
    date: "2026-03-08",
    bank: "Kotak Bank",
    mode: "IMPS",
    acc: "888899990000",
    ifsc: "KKBK0005678",
    type: "Education Loan",
  },
];

export const DISBURSEMENT_PAID_DVS = [
  {
    dvNo: "DV-0999",
    loanId: "LN-2024-008",
    customer: "Rahul Verma",
    amount: 500000,
    status: "paid",
    date: "2026-03-07",
    bank: "HDFC Bank",
    mode: "RTGS",
    acc: "111222333444",
    ifsc: "HDFC0008888",
    type: "Home Loan",
  },
  {
    dvNo: "DV-1003",
    loanId: "LN-2024-009",
    customer: "Ravi Sharma",
    amount: 350000,
    status: "paid",
    date: "2026-03-06",
    bank: "ICICI Bank",
    mode: "NEFT",
    acc: "777788889999",
    ifsc: "ICIC0001234",
    type: "Personal Loan",
  },
];

// EMI Management Page Data
export const EMI_APPROVED_LOANS = [
  {
    id: "LA-EMI-001",
    loanNumber: "LON-2026-001",
    applicantName: "Rajesh Kumar",
    tenureMonths: 24,
    interestRate: 10.5,
    approvedAmount: 500000,
    applicationStatus: "APPROVED",
    approvedDate: "2026-03-05",
  },
  {
    id: "LA-EMI-002",
    loanNumber: "LON-2026-002",
    applicantName: "Vikram Singh",
    tenureMonths: 24,
    interestRate: 10.0,
    approvedAmount: 600000,
    applicationStatus: "APPROVED",
    approvedDate: "2026-03-01",
  },
  {
    id: "LA-EMI-003",
    loanNumber: "LON-2026-003",
    applicantName: "Amit Patel",
    tenureMonths: 36,
    interestRate: 9.5,
    approvedAmount: 750000,
    applicationStatus: "APPROVED",
    approvedDate: "2026-03-07",
  },
];

export const EMI_VOUCHERS = [
  {
    id: "EMV-001",
    voucherNo: "EMV-2026-001",
    loanNumber: "LON-2026-001",
    customerName: "Rajesh Kumar",
    tenure: 24,
    interestRate: 10.5,
    amount: 500000,
    paidAmount: 23150,
    status: "ACTIVE",
    startDate: "2026-03-10",
  },
  {
    id: "EMV-002",
    voucherNo: "EMV-2026-002",
    loanNumber: "LON-2026-002",
    customerName: "Vikram Singh",
    tenure: 24,
    interestRate: 10.0,
    amount: 600000,
    paidAmount: 27640,
    status: "ACTIVE",
    startDate: "2026-03-05",
  },
  {
    id: "EMV-003",
    voucherNo: "EMV-2026-003",
    loanNumber: "LON-2026-003",
    customerName: "Amit Patel",
    tenure: 36,
    interestRate: 9.5,
    amount: 750000,
    paidAmount: 0,
    status: "PENDING",
    startDate: "2026-03-11",
  },
];

// Technical Review Page Data
export const TECHNICAL_REVIEW_STATISTICS = [
  {
    id: 1,
    title: "Total Reports",
    value: "234",
    iconName: "FileText",
    iconColor: "blue",
    subtext: "+12.5% from last month",
    trend: "up",
  },
  {
    id: 2,
    title: "Approved",
    value: "156",
    iconName: "CheckCircle",
    iconColor: "green",
    subtext: "67% approval rate",
    trend: "up",
  },
  {
    id: 3,
    title: "Pending Review",
    value: "48",
    iconName: "Clock",
    iconColor: "orange",
    subtext: "Avg. 3 days waiting",
    trend: "down",
  },
  {
    id: 4,
    title: "Rejected",
    value: "30",
    iconName: "XCircle",
    iconColor: "red",
    subtext: "13% rejection rate",
    trend: "down",
  },
];

export const TECHNICAL_REVIEW_REPORTS = [
  {
    id: 1,
    engineerName: "Rajesh Kumar",
    agencyName: "Valuation Experts Ltd",
    propertyType: "Residential",
    city: "Mumbai",
    state: "Maharashtra",
    marketValue: "₹1,25,00,000",
    recommendedLtv: "75%",
    constructionStatus: "Completed",
    qualityOfConstruction: "Excellent",
    status: "approved",
    address: "15, Marine Drive, South Mumbai",
    pincode: "400001",
    discussionValue: "₹1,20,00,000",
    forcesdSaleValue: "₹1,10,00,000",
    propertyAge: "5",
    residualLife: "55",
    remarks:
      "Property is in prime location with excellent construction quality",
    reportUrl: "https://example.com/report1",
    sitePhotographs: "https://example.com/photos1",
    submittedDate: "2024-02-15",
    lastUpdated: "2024-02-16",
  },
  {
    id: 2,
    engineerName: "Priya Sharma",
    agencyName: "City Valuers",
    propertyType: "Commercial",
    city: "Delhi",
    state: "Delhi NCR",
    marketValue: "₹2,50,00,000",
    recommendedLtv: "70%",
    constructionStatus: "Under Construction",
    qualityOfConstruction: "Good",
    status: "pending",
    address: "Cyber City, Sector 24",
    pincode: "122001",
    discussionValue: "₹2,40,00,000",
    forcesdSaleValue: "₹2,25,00,000",
    propertyAge: "2",
    residualLife: "48",
    remarks: "Upcoming commercial hub with good appreciation potential",
    reportUrl: "https://example.com/report2",
    sitePhotographs: "https://example.com/photos2",
    submittedDate: "2024-02-14",
    lastUpdated: "2024-02-15",
  },
  {
    id: 3,
    engineerName: "Amit Patel",
    agencyName: "Property Assessors Inc",
    propertyType: "Industrial",
    city: "Bangalore",
    state: "Karnataka",
    marketValue: "₹3,75,00,000",
    recommendedLtv: "65%",
    constructionStatus: "Completed",
    qualityOfConstruction: "Average",
    status: "rejected",
    address: "Whitefield Industrial Area",
    pincode: "560066",
    discussionValue: "₹3,60,00,000",
    forcesdSaleValue: "₹3,40,00,000",
    propertyAge: "8",
    residualLife: "32",
    remarks: "Located in established industrial zone but requires maintenance",
    reportUrl: "https://example.com/report3",
    sitePhotographs: "https://example.com/photos3",
    submittedDate: "2024-02-13",
    lastUpdated: "2024-02-14",
  },
  {
    id: 4,
    engineerName: "Sneha Reddy",
    agencyName: "Prime Valuations",
    propertyType: "Land",
    city: "Hyderabad",
    state: "Telangana",
    marketValue: "₹95,00,000",
    recommendedLtv: "60%",
    constructionStatus: "Not Applicable",
    qualityOfConstruction: "Good",
    status: "approved",
    address: "Financial District, Gachibowli",
    pincode: "500032",
    discussionValue: "₹90,00,000",
    forcesdSaleValue: "₹85,00,000",
    propertyAge: "0",
    residualLife: "99",
    remarks: "Prime location for commercial development",
    reportUrl: "https://example.com/report4",
    sitePhotographs: "https://example.com/photos4",
    submittedDate: "2024-02-12",
    lastUpdated: "2024-02-13",
  },
  {
    id: 5,
    engineerName: "Vikram Mehta",
    agencyName: "Accurate Assessors",
    propertyType: "Residential",
    city: "Pune",
    state: "Maharashtra",
    marketValue: "₹85,00,000",
    recommendedLtv: "80%",
    constructionStatus: "Completed",
    qualityOfConstruction: "Excellent",
    status: "pending",
    address: "Koregaon Park",
    pincode: "411001",
    discussionValue: "₹82,00,000",
    forcesdSaleValue: "₹78,00,000",
    propertyAge: "3",
    residualLife: "67",
    remarks: "Premium residential area with high demand",
    reportUrl: "https://example.com/report5",
    sitePhotographs: "https://example.com/photos5",
    submittedDate: "2024-02-11",
    lastUpdated: "2024-02-12",
  },
];

// Sanction Page Data
export const SANCTION_STATISTICS = [
  {
    id: 1,
    title: "Total Sanctions",
    value: "1,234",
    iconName: "FileCheck",
    iconColor: "blue",
    subtext: "+12.5% from last month",
    trend: "up",
  },
  {
    id: 2,
    title: "Sanctioned Loans",
    value: "876",
    iconName: "CheckCircle",
    iconColor: "green",
    subtext: "71% success rate",
    trend: "up",
  },
  {
    id: 3,
    title: "Pending Sanctions",
    value: "245",
    iconName: "Clock",
    iconColor: "orange",
    subtext: "Avg. 3 days waiting",
    trend: "neutral",
  },
  {
    id: 4,
    title: "Rejected",
    value: "113",
    iconName: "XCircle",
    iconColor: "red",
    subtext: "9% rejection rate",
    trend: "down",
  },
];

export const SANCTION_REPORTS = [
  {
    id: 1,
    loanNumber: "LN-2024-001",
    applicantName: "Rajesh Kumar",
    loanType: "Home Loan",
    requestedAmount: "₹45,00,000",
    sanctionedAmount: "₹42,00,000",
    interestRate: "8.5%",
    tenure: "240 months",
    branch: "Mumbai Main",
    status: "sanctioned",
    sanctionDate: "2024-02-15",
    requestedTenure: "240 months",
    requestedInterest: "8.75%",
    emiAmount: "₹36,500",
    processingFee: "₹25,000",
    insuranceAmount: "₹45,000",
    sanctionAuthority: "Suresh Patel - VP",
    validityDate: "2024-05-15",
    conditions: "Property valuation to be completed within 30 days",
    remarks: "Approved with standard terms",
  },
  {
    id: 2,
    loanNumber: "LN-2024-002",
    applicantName: "Priya Sharma",
    loanType: "Personal Loan",
    requestedAmount: "₹15,00,000",
    sanctionedAmount: "₹12,00,000",
    interestRate: "10.5%",
    tenure: "60 months",
    branch: "Delhi NCR",
    status: "pending",
    sanctionDate: "2024-02-14",
    requestedTenure: "48 months",
    requestedInterest: "10.25%",
    emiAmount: "₹25,800",
    processingFee: "₹10,000",
    insuranceAmount: "₹18,000",
    sanctionAuthority: "Pending",
    validityDate: "2024-05-14",
    conditions: "Income verification pending",
    remarks: "Under review by credit committee",
  },
  {
    id: 3,
    loanNumber: "LN-2024-003",
    applicantName: "Amit Patel",
    loanType: "Business Loan",
    requestedAmount: "₹75,00,000",
    sanctionedAmount: "₹60,00,000",
    interestRate: "9.75%",
    tenure: "120 months",
    branch: "Bangalore",
    status: "conditional",
    sanctionDate: "2024-02-13",
    requestedTenure: "84 months",
    requestedInterest: "9.5%",
    emiAmount: "₹64,500",
    processingFee: "₹45,000",
    insuranceAmount: "₹75,000",
    sanctionAuthority: "Meera Reddy - AVP",
    validityDate: "2024-05-13",
    conditions: "Additional collateral required",
    remarks: "Conditional approval subject to collateral",
  },
  {
    id: 4,
    loanNumber: "LN-2024-004",
    applicantName: "Sneha Reddy",
    loanType: "Home Loan",
    requestedAmount: "₹35,00,000",
    sanctionedAmount: "₹32,00,000",
    interestRate: "8.25%",
    tenure: "180 months",
    branch: "Hyderabad",
    status: "rejected",
    sanctionDate: "2024-02-12",
    requestedTenure: "180 months",
    requestedInterest: "8.5%",
    emiAmount: "₹29,500",
    processingFee: "₹20,000",
    insuranceAmount: "₹35,000",
    sanctionAuthority: "Vikram Singh - Manager",
    validityDate: "2024-05-12",
    conditions: "N/A",
    remarks: "Rejected due to low credit score",
  },
  {
    id: 5,
    loanNumber: "LN-2024-005",
    applicantName: "Vikram Mehta",
    loanType: "Car Loan",
    requestedAmount: "₹12,00,000",
    sanctionedAmount: "₹10,50,000",
    interestRate: "9.0%",
    tenure: "84 months",
    branch: "Pune",
    status: "sanctioned",
    sanctionDate: "2024-02-11",
    requestedTenure: "72 months",
    requestedInterest: "9.25%",
    emiAmount: "₹16,800",
    processingFee: "₹8,000",
    insuranceAmount: "₹12,000",
    sanctionAuthority: "Anjali Desai - Manager",
    validityDate: "2024-05-11",
    conditions: "Vehicle insurance mandatory",
    remarks: "Approved with standard terms",
  },
  {
    id: 6,
    loanNumber: "LN-2024-006",
    applicantName: "Neha Gupta",
    loanType: "Home Loan",
    requestedAmount: "₹55,00,000",
    sanctionedAmount: "₹50,00,000",
    interestRate: "8.4%",
    tenure: "240 months",
    branch: "Mumbai Main",
    status: "sanctioned",
    sanctionDate: "2024-02-10",
    requestedTenure: "240 months",
    requestedInterest: "8.6%",
    emiAmount: "₹43,200",
    processingFee: "₹30,000",
    insuranceAmount: "₹55,000",
    sanctionAuthority: "Suresh Patel - VP",
    validityDate: "2024-05-10",
    conditions: "Property valuation to be completed within 30 days",
    remarks: "Approved with standard terms",
  },
  {
    id: 7,
    loanNumber: "LN-2024-007",
    applicantName: "Rahul Verma",
    loanType: "Business Loan",
    requestedAmount: "₹85,00,000",
    sanctionedAmount: "₹75,00,000",
    interestRate: "9.5%",
    tenure: "120 months",
    branch: "Delhi NCR",
    status: "pending",
    sanctionDate: "2024-02-09",
    requestedTenure: "96 months",
    requestedInterest: "9.25%",
    emiAmount: "₹78,500",
    processingFee: "₹50,000",
    insuranceAmount: "₹85,000",
    sanctionAuthority: "Pending",
    validityDate: "2024-05-09",
    conditions: "Business financials verification pending",
    remarks: "Under review",
  },
  {
    id: 8,
    loanNumber: "LN-2024-008",
    applicantName: "Pooja Singh",
    loanType: "Personal Loan",
    requestedAmount: "₹8,00,000",
    sanctionedAmount: "₹6,50,000",
    interestRate: "11.0%",
    tenure: "48 months",
    branch: "Bangalore",
    status: "conditional",
    sanctionDate: "2024-02-08",
    requestedTenure: "36 months",
    requestedInterest: "10.75%",
    emiAmount: "₹16,800",
    processingFee: "₹6,000",
    insuranceAmount: "₹8,000",
    sanctionAuthority: "Meera Reddy - AVP",
    validityDate: "2024-05-08",
    conditions: "Additional income proof required",
    remarks: "Conditional approval",
  },
];

export const SANCTION_LOAN_TYPES = [
  "all",
  "Home Loan",
  "Personal Loan",
  "Business Loan",
  "Car Loan",
  "Education Loan",
];

// Legal Compliance Page Data
export const LEGAL_COMPLIANCE_STATISTICS = [
  {
    id: 1,
    title: "Total Reports",
    value: "156",
    iconName: "FileText",
    iconColor: "blue",
    subtext: "+12 this month",
    trend: "up",
  },
  {
    id: 2,
    title: "Approved",
    value: "98",
    iconName: "CheckCircle",
    iconColor: "green",
    subtext: "63% approval rate",
    trend: "up",
  },
  {
    id: 3,
    title: "Pending",
    value: "42",
    iconName: "Clock",
    iconColor: "orange",
    subtext: "27% pending",
    trend: "neutral",
  },
  {
    id: 4,
    title: "Rejected",
    value: "16",
    iconName: "XCircle",
    iconColor: "red",
    subtext: "10% rejection",
    trend: "down",
  },
];

export const LEGAL_COMPLIANCE_REPORTS = [
  {
    id: 1,
    engineerName: "John Smith",
    agencyName: "Prime Properties",
    propertyType: "Residential",
    city: "Mumbai",
    state: "Maharashtra",
    marketValue: "₹85,00,000",
    recommendedLtv: "75%",
    constructionStatus: "Completed",
    qualityOfConstruction: "Excellent",
    status: "approved",
    address: "15, Marine Drive, South Mumbai",
    pincode: "400001",
    submittedDate: "2024-02-15",
    lastUpdated: "2024-02-16",
  },
  {
    id: 2,
    engineerName: "Sarah Johnson",
    agencyName: "City Developers",
    propertyType: "Commercial",
    city: "Delhi",
    state: "Delhi NCR",
    marketValue: "₹1,25,00,000",
    recommendedLtv: "70%",
    constructionStatus: "Under Construction",
    qualityOfConstruction: "Good",
    status: "pending",
    address: "Cyber City, Sector 24",
    pincode: "122001",
    submittedDate: "2024-02-14",
    lastUpdated: "2024-02-15",
  },
  {
    id: 3,
    engineerName: "Mike Chen",
    agencyName: "Metro Realtors",
    propertyType: "Industrial",
    city: "Bangalore",
    state: "Karnataka",
    marketValue: "₹2,50,00,000",
    recommendedLtv: "65%",
    constructionStatus: "Completed",
    qualityOfConstruction: "Average",
    status: "rejected",
    address: "Whitefield Industrial Area",
    pincode: "560066",
    submittedDate: "2024-02-13",
    lastUpdated: "2024-02-14",
  },
  {
    id: 4,
    engineerName: "Priya Patel",
    agencyName: "LegalEagle Associates",
    propertyType: "Residential",
    city: "Pune",
    state: "Maharashtra",
    marketValue: "₹65,00,000",
    recommendedLtv: "80%",
    constructionStatus: "Completed",
    qualityOfConstruction: "Good",
    status: "approved",
    address: "Koregaon Park",
    pincode: "411001",
    submittedDate: "2024-02-12",
    lastUpdated: "2024-02-13",
  },
  {
    id: 5,
    engineerName: "Alex Rodriguez",
    agencyName: "Global Realtors",
    propertyType: "Commercial",
    city: "Chennai",
    state: "Tamil Nadu",
    marketValue: "₹1,80,00,000",
    recommendedLtv: "68%",
    constructionStatus: "Completed",
    qualityOfConstruction: "Excellent",
    status: "approved",
    address: "OMR, Siruseri",
    pincode: "603103",
    submittedDate: "2024-02-11",
    lastUpdated: "2024-02-12",
  },
];

// KYC Verification Page - Applications List
export const KYC_APPLICATIONS = [
  {
    id: "KYC-001",
    loanNumber: "LON-2024-1001",
    applicantName: "Rajesh Kumar",
    documents: {
      aadhaar: "/uploads/aadhaar.jpg",
      pan: "/uploads/pan.jpg",
      salary_slip: "/uploads/salary.pdf",
    },
    cibilScore: 785,
    applicationDate: "2026-03-05",
    risk: "Low",
    status: "KYC_PENDING",
    kycStatus: "kyc_pending",
  },
  {
    id: "KYC-002",
    loanNumber: "LON-2024-1002",
    applicantName: "Priya Sharma",
    documents: { aadhaar: "/uploads/aadhaar2.jpg", pan: "/uploads/pan2.jpg" },
    cibilScore: 725,
    applicationDate: "2026-03-08",
    risk: "Low",
    status: "KYC_PENDING",
    kycStatus: "kyc_pending",
  },
  {
    id: "KYC-003",
    loanNumber: "LON-2024-1003",
    applicantName: "Amit Patel",
    documents: {
      aadhaar: "/uploads/aadhaar3.jpg",
      pan: "/uploads/pan3.jpg",
      bank_statement: "/uploads/bank.pdf",
    },
    cibilScore: 810,
    applicationDate: "2026-03-05",
    risk: "Low",
    status: "VERIFIED",
    kycStatus: "approved",
  },
  {
    id: "KYC-004",
    loanNumber: "LON-2024-1004",
    applicantName: "Sneha Desai",
    documents: { aadhaar: "/uploads/aadhaar4.jpg" },
    cibilScore: 590,
    applicationDate: "2026-02-28",
    risk: "High",
    status: "REJECTED",
    kycStatus: "rejected",
  },
  {
    id: "KYC-005",
    loanNumber: "LON-2024-1005",
    applicantName: "Vikram Singh",
    documents: {
      aadhaar: "/uploads/aadhaar5.jpg",
      pan: "/uploads/pan5.jpg",
      address_proof: "/uploads/addr.pdf",
    },
    cibilScore: 755,
    applicationDate: "2026-03-09",
    risk: "Low",
    status: "KYC_PENDING",
    kycStatus: "kyc_pending",
  },
  {
    id: "KYC-006",
    loanNumber: "LON-2024-1006",
    applicantName: "Sunita Verma",
    documents: { aadhaar: "/uploads/aadhaar6.jpg", pan: "/uploads/pan6.jpg" },
    cibilScore: 640,
    applicationDate: "2026-03-07",
    risk: "High",
    status: "REJECTED",
    kycStatus: "rejected",
  },
];

// KYC Verification Page Data
export const KYC_CIBIL_DATA = {
  score: 750,
  lastUpdated: "2025-02-09",
  band: "Good",
  factors: [
    { name: "Credit Utilization", score: 85, status: "good" },
    { name: "Payment History", score: 92, status: "good" },
    { name: "Credit Age", score: 65, status: "average" },
    { name: "Credit Mix", score: 78, status: "good" },
    { name: "Recent Inquiries", score: 45, status: "poor" },
  ],
  loans: [
    {
      type: "Personal Loan",
      amount: "₹2,50,000",
      status: "Active",
      emi: "₹8,500",
    },
    {
      type: "Credit Card",
      limit: "₹1,00,000",
      utilized: "₹35,000",
      status: "Active",
    },
    {
      type: "Home Loan",
      amount: "₹45,00,000",
      status: "Active",
      emi: "₹38,000",
    },
  ],
  inquiries: [
    { date: "2025-01-15", lender: "HDFC Bank", type: "Personal Loan" },
    { date: "2024-12-20", lender: "ICICI Bank", type: "Credit Card" },
    { date: "2024-11-05", lender: "Axis Bank", type: "Car Loan" },
  ],
};

// Document Page Defaults (fallback values for API-driven docs)
export const DOCUMENT_PAGE_DEFAULTS = {
  status: "PENDING",
  uploadDate: "-",
  applicantType: "APPLICANT",
};

// Document Verification Page Data
export const DOCUMENT_APPLICATIONS = [
  {
    id: "DOC-001",
    loanNumber: "LON-2024-1001",
    applicationNumber: "APP-2024-1001",
    applicantName: "Rajesh Kumar",
    coApplicantName: "Priya Kumar",
    loanAmount: 2500000,
    currentStage: "Document Verification",
    totalDocuments: 8,
  },
  {
    id: "DOC-002",
    loanNumber: "LON-2024-1002",
    applicationNumber: "APP-2024-1002",
    applicantName: "Amit Sharma",
    coApplicantName: null,
    loanAmount: 500000,
    currentStage: "Document Verification",
    totalDocuments: 6,
  },
  {
    id: "DOC-003",
    loanNumber: "LON-2024-1003",
    applicationNumber: "APP-2024-1003",
    applicantName: "Sunita Patel",
    coApplicantName: "Rahul Patel",
    loanAmount: 1000000,
    currentStage: "Document Verification",
    totalDocuments: 10,
  },
  {
    id: "DOC-004",
    loanNumber: "LON-2024-1004",
    applicationNumber: "APP-2024-1004",
    applicantName: "Vikram Singh",
    coApplicantName: null,
    loanAmount: 750000,
    currentStage: "Document Verification",
    totalDocuments: 7,
  },
  {
    id: "DOC-005",
    loanNumber: "LON-2024-1005",
    applicationNumber: "APP-2024-1005",
    applicantName: "Sneha Desai",
    coApplicantName: "Karan Desai",
    loanAmount: 1200000,
    currentStage: "Document Verification",
    totalDocuments: 9,
  },
];

export const DOCUMENT_REPOSITORY = {
  "DOC-001": [
    {
      id: 1,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_rajesh.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-05",
    },
    {
      id: 2,
      name: "PAN Card",
      url: "/uploads/pan_rajesh.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-05",
    },
    {
      id: 3,
      name: "Salary Slip",
      url: "/uploads/salary_rajesh.pdf",
      status: "PENDING",
      category: "income_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-06",
    },
    {
      id: 4,
      name: "Bank Statement",
      url: "/uploads/bank_rajesh.pdf",
      status: "VERIFIED",
      category: "bank_statement",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-06",
    },
    {
      id: 5,
      name: "Address Proof",
      url: "/uploads/address_rajesh.pdf",
      status: "VERIFIED",
      category: "address_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-07",
    },
    {
      id: 6,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_priya.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-07",
    },
    {
      id: 7,
      name: "PAN Card",
      url: "/uploads/pan_priya.pdf",
      status: "PENDING",
      category: "identity_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-08",
    },
    {
      id: 8,
      name: "Income Tax Return",
      url: "/uploads/itr_priya.pdf",
      status: "VERIFIED",
      category: "income_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-08",
    },
  ],
  "DOC-002": [
    {
      id: 1,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_amit.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-04",
    },
    {
      id: 2,
      name: "PAN Card",
      url: "/uploads/pan_amit.pdf",
      status: "REJECTED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-04",
    },
    {
      id: 3,
      name: "Salary Slip",
      url: "/uploads/salary_amit.pdf",
      status: "VERIFIED",
      category: "income_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-05",
    },
    {
      id: 4,
      name: "Bank Statement",
      url: "/uploads/bank_amit.pdf",
      status: "PENDING",
      category: "bank_statement",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-06",
    },
  ],
  "DOC-003": [
    {
      id: 1,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_sunita.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-03",
    },
    {
      id: 2,
      name: "PAN Card",
      url: "/uploads/pan_sunita.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-03",
    },
    {
      id: 3,
      name: "Business Proof",
      url: "/uploads/business_sunita.pdf",
      status: "VERIFIED",
      category: "business_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-04",
    },
    {
      id: 4,
      name: "GST Certificate",
      url: "/uploads/gst_sunita.pdf",
      status: "PENDING",
      category: "business_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-04",
    },
    {
      id: 5,
      name: "Bank Statement",
      url: "/uploads/bank_sunita.pdf",
      status: "VERIFIED",
      category: "bank_statement",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-05",
    },
    {
      id: 6,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_rahul.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-05",
    },
    {
      id: 7,
      name: "PAN Card",
      url: "/uploads/pan_rahul.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-06",
    },
    {
      id: 8,
      name: "Business Proof",
      url: "/uploads/business_rahul.pdf",
      status: "PENDING",
      category: "business_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-06",
    },
  ],
  "DOC-004": [
    {
      id: 1,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_vikram.pdf",
      status: "PENDING",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-08",
    },
    {
      id: 2,
      name: "PAN Card",
      url: "/uploads/pan_vikram.pdf",
      status: "PENDING",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-08",
    },
    {
      id: 3,
      name: "Salary Slip",
      url: "/uploads/salary_vikram.pdf",
      status: "PENDING",
      category: "income_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-09",
    },
  ],
  "DOC-005": [
    {
      id: 1,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_sneha.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-02",
    },
    {
      id: 2,
      name: "PAN Card",
      url: "/uploads/pan_sneha.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-02",
    },
    {
      id: 3,
      name: "Property Documents",
      url: "/uploads/property_sneha.pdf",
      status: "VERIFIED",
      category: "property_documents",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-03",
    },
    {
      id: 4,
      name: "Bank Statement",
      url: "/uploads/bank_sneha.pdf",
      status: "VERIFIED",
      category: "bank_statement",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-04",
    },
    {
      id: 5,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_karan.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-04",
    },
    {
      id: 6,
      name: "PAN Card",
      url: "/uploads/pan_karan.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-05",
    },
    {
      id: 7,
      name: "Salary Slip",
      url: "/uploads/salary_karan.pdf",
      status: "VERIFIED",
      category: "income_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-06",
    },
  ],
};

// leads page dummy data
export const LEADS_PAGE_DUMMY_CONFIG = {
  ITEMS_PER_PAGE: 6,
  MAX_VISIBLE_PAGES: 5,
};

export const LEAD_ACTION_DEFINITIONS = [
  {
    key: "edit",
    label: "Edit",
    icon: "Edit",
  },
  {
    key: "charges",
    label: "Edit Login Fee",
    icon: "DollarSign",
  },
  {
    key: "delete",
    label: "Delete",
    icon: "Trash2",
  },
];

export const LEADS_DUMMY_DATA = [
  {
    id: "lead-1",
    leadNumber: "LD0001",
    fullName: "Rahul Sharma",
    contactNumber: "9876543210",
    email: "rahul.sharma@gmail.com",
    city: "Jaipur",
    state: "Rajasthan",
    loanAmount: 300000,
    loanType: { name: "Home Loan" },
    createdAt: "2026-03-10T09:30:00.000Z",
  },
  {
    id: "lead-2",
    leadNumber: "LD0002",
    fullName: "Priya Singh",
    contactNumber: "9988776655",
    email: "priya.singh@gmail.com",
    city: "Delhi",
    state: "Delhi",
    loanAmount: 500000,
    loanType: { name: "Personal Loan" },
    createdAt: "2026-03-09T14:45:00.000Z",
  },
  {
    id: "lead-3",
    leadNumber: "LD0003",
    fullName: "Amit Verma",
    contactNumber: "9123456789",
    email: "amit.verma@gmail.com",
    city: "Mumbai",
    state: "Maharashtra",
    loanAmount: 1200000,
    loanType: { name: "Business Loan" },
    createdAt: "2026-03-08T11:20:00.000Z",
  },
  {
    id: "lead-4",
    leadNumber: "LD0004",
    fullName: "Sneha Patel",
    contactNumber: "9012345678",
    email: "sneha.patel@gmail.com",
    city: "Ahmedabad",
    state: "Gujarat",
    loanAmount: 800000,
    loanType: { name: "Car Loan" },
    createdAt: "2026-03-07T16:00:00.000Z",
  },
  {
    id: "lead-5",
    leadNumber: "LD0005",
    fullName: "Mohit Gupta",
    contactNumber: "9098765432",
    email: "mohit.gupta@gmail.com",
    city: "Lucknow",
    state: "Uttar Pradesh",
    loanAmount: 250000,
    loanType: { name: "Education Loan" },
    createdAt: "2026-03-06T10:15:00.000Z",
  },
];

export const getLeadLoanTypeColor = (name = "") => {
  const key = name.toLowerCase();

  if (key.includes("home")) return "bg-blue-50 text-blue-700 border-blue-200";
  if (key.includes("personal"))
    return "bg-purple-50 text-purple-700 border-purple-200";
  if (key.includes("car")) return "bg-green-50 text-green-700 border-green-200";
  if (key.includes("business"))
    return "bg-amber-50 text-amber-700 border-amber-200";
  if (key.includes("education"))
    return "bg-indigo-50 text-indigo-700 border-indigo-200";

  return "bg-gray-50 text-gray-700 border-gray-200";
};
