export const APPLICATION_FORM_INITIAL_DATA = {
  name: "",
  email: "",
  phone: "",
  income: "",
  address: "",
  aadhaar: "",
  pan: "",
  cibil: "",
  amount: "",
  tenure: "12",
  interest: "10.5",
  occupation: "",
  loanType: "Personal Loan",
};

export const SAMPLE_LOAN_APPLICATIONS = [
  {
    id: 1,
    customer: {
      firstName: "Rajesh",
      lastName: "Kumar",
      email: "rajesh.kumar@email.com",
      contactNumber: "+91 98765 43210",
      panNumber: "ABCDE1234F",
      aadhaarNumber: "1234 5678 9012",
      address: "123, MG Road, Bangalore, Karnataka - 560001",
      occupation: "Software Engineer",
      monthlyIncome: "850000",
    },
    requestedAmount: "500000",
    tenureMonths: "24",
    interestRate: "10.5",
    cibilScore: 780,
    loanType: "Personal Loan",
    status: "APPROVED",
    appliedDate: "2026-03-01",
    approvedDate: "2026-03-05",
  },
  {
    id: 2,
    customer: {
      firstName: "Priya",
      lastName: "Sharma",
      email: "priya.sharma@email.com",
      contactNumber: "+91 87654 32109",
      panNumber: "FGHIJ5678K",
      aadhaarNumber: "2345 6789 0123",
      address: "45/B, Park Street, Mumbai, Maharashtra - 400001",
      occupation: "Marketing Manager",
      monthlyIncome: "650000",
    },
    requestedAmount: "300000",
    tenureMonths: "12",
    interestRate: "11.0",
    cibilScore: 725,
    loanType: "Personal Loan",
    status: "PENDING",
    appliedDate: "2026-03-08",
  },
  {
    id: 3,
    customer: {
      firstName: "Amit",
      lastName: "Patel",
      email: "amit.patel@email.com",
      contactNumber: "+91 76543 21098",
      panNumber: "KLMNO9012P",
      aadhaarNumber: "3456 7890 1234",
      address: "78, CG Road, Ahmedabad, Gujarat - 380009",
      occupation: "Business Owner",
      monthlyIncome: "1200000",
    },
    requestedAmount: "750000",
    tenureMonths: "36",
    interestRate: "9.5",
    cibilScore: 810,
    loanType: "Business Loan",
    status: "UNDER_REVIEW",
    appliedDate: "2026-03-05",
  },
  {
    id: 4,
    customer: {
      firstName: "Sneha",
      lastName: "Desai",
      email: "sneha.desai@email.com",
      contactNumber: "+91 65432 10987",
      panNumber: "PQRST3456U",
      aadhaarNumber: "4567 8901 2345",
      address: "12, Anna Salai, Chennai, Tamil Nadu - 600002",
      occupation: "Teacher",
      monthlyIncome: "450000",
    },
    requestedAmount: "200000",
    tenureMonths: "18",
    interestRate: "12.0",
    cibilScore: 690,
    loanType: "Personal Loan",
    status: "REJECTED",
    appliedDate: "2026-02-28",
    rejectedDate: "2026-03-02",
    rejectionReason: "Insufficient income",
  },
  {
    id: 5,
    customer: {
      firstName: "Vikram",
      lastName: "Singh",
      email: "vikram.singh@email.com",
      contactNumber: "+91 54321 09876",
      panNumber: "UVWXY7890Z",
      aadhaarNumber: "5678 9012 3456",
      address: "89/C, Connaught Place, New Delhi, Delhi - 110001",
      occupation: "Financial Analyst",
      monthlyIncome: "950000",
    },
    requestedAmount: "600000",
    tenureMonths: "24",
    interestRate: "10.0",
    cibilScore: 755,
    loanType: "Personal Loan",
    status: "APPROVED",
    appliedDate: "2026-02-25",
    approvedDate: "2026-03-01",
  },
];

// Credit Check Page Data
export const CREDIT_CHECK_LOAN_APPLICATIONS = [
  {
    id: "LN-2024-1256",
    applicationNumber: "LN-2024-1256",
    loanNumber: "LON-2024-001",
    applicantName: "Rajesh Kumar",
    coApplicantName: "Priya Kumar",
    loanType: "Home Loan",
    loanAmount: 2500000,
    branchName: "Mumbai Central",
    currentStage: "Credit Check",
    monthlyIncome: 150000,
    panNumber: "ABCDE1234F",
    dob: "15-08-1985",
    mobile: "+91 9876543210",
    employmentType: "Salaried",
    companyName: "Tech Solutions Pvt Ltd",
    tenure: 20,
    interestRate: 8.5,
  },
  {
    id: "LN-2024-1257",
    applicationNumber: "LN-2024-1257",
    loanNumber: "LON-2024-002",
    applicantName: "Amit Sharma",
    coApplicantName: null,
    loanType: "Personal Loan",
    loanAmount: 500000,
    branchName: "Delhi North",
    currentStage: "Credit Check",
    monthlyIncome: 75000,
    panNumber: "EFGHI5678J",
    dob: "20-05-1990",
    mobile: "+91 9876543212",
    employmentType: "Salaried",
    companyName: "Finance Corp",
    tenure: 5,
    interestRate: 12.5,
  },
  {
    id: "LN-2024-1258",
    applicationNumber: "LN-2024-1258",
    loanNumber: "LON-2024-003",
    applicantName: "Sunita Patel",
    coApplicantName: "Rahul Patel",
    loanType: "Business Loan",
    loanAmount: 1000000,
    branchName: "Ahmedabad West",
    currentStage: "Credit Check",
    monthlyIncome: 200000,
    panNumber: "JKLMN9012O",
    dob: "12-12-1980",
    mobile: "+91 9876543213",
    employmentType: "Self-Employed",
    companyName: "Patel Traders",
    tenure: 10,
    interestRate: 10.5,
  },
];

export const CREDIT_CHECK_DATA = {
  "LON-2024-001": {
    creditScores: [
      { bureau: "CIBIL", score: 785, status: "Excellent", color: "emerald" },
      { bureau: "Experian", score: 780, status: "Excellent", color: "emerald" },
      { bureau: "Equifax", score: 765, status: "Good", color: "blue" },
      { bureau: "CRIF", score: 790, status: "Excellent", color: "emerald" },
    ],
    coApplicant: {
      name: "Priya Kumar",
      panNumber: "PQRST5678G",
      dob: "22-11-1988",
      mobile: "+91 9876543211",
      creditScore: 720,
      riskCategory: "Low Risk",
      employmentType: "Self-Employed",
      monthlyIncome: 90000,
    },
    existingLoans: [
      {
        id: 1,
        loanType: "Home Loan",
        bankName: "HDFC Bank",
        emiAmount: 25000,
        outstandingAmount: 1850000,
        overdueAmount: 0,
        status: "Active",
        statusColor: "emerald",
      },
      {
        id: 2,
        loanType: "Car Loan",
        bankName: "ICICI Bank",
        emiAmount: 12000,
        outstandingAmount: 320000,
        overdueAmount: 0,
        status: "Active",
        statusColor: "emerald",
      },
    ],
    creditAnalysis: {
      monthlyIncome: 150000,
      totalExistingEMI: 50000,
      foirPercentage: 33.33,
      eligibleEMICapacity: 75000,
      riskGrade: "B+",
      recommendedLoanAmount: 2250000,
      recommendedTenure: 20,
      interestRate: 8.5,
      creditRemarks:
        "Applicant has good credit score with manageable existing liabilities. FOIR within acceptable limits.",
    },
  },
  "LON-2024-002": {
    creditScores: [
      { bureau: "CIBIL", score: 650, status: "Fair", color: "blue" },
      { bureau: "Experian", score: 670, status: "Fair", color: "blue" },
      { bureau: "Equifax", score: 630, status: "Fair", color: "amber" },
      { bureau: "CRIF", score: 640, status: "Fair", color: "blue" },
    ],
    coApplicant: null,
    existingLoans: [
      {
        id: 1,
        loanType: "Personal Loan",
        bankName: "Axis Bank",
        emiAmount: 8000,
        outstandingAmount: 150000,
        overdueAmount: 15000,
        status: "Default",
        statusColor: "rose",
      },
    ],
    creditAnalysis: {
      monthlyIncome: 75000,
      totalExistingEMI: 8000,
      foirPercentage: 10.67,
      eligibleEMICapacity: 37500,
      riskGrade: "C",
      recommendedLoanAmount: 400000,
      recommendedTenure: 5,
      interestRate: 12.5,
      creditRemarks:
        "Applicant has average credit score with some overdue payments. Requires further verification.",
    },
  },
  "LON-2024-003": {
    creditScores: [
      { bureau: "CIBIL", score: 720, status: "Good", color: "blue" },
      { bureau: "Experian", score: 710, status: "Good", color: "blue" },
      { bureau: "Equifax", score: 730, status: "Good", color: "blue" },
      { bureau: "CRIF", score: 715, status: "Good", color: "blue" },
    ],
    coApplicant: {
      name: "Rahul Patel",
      panNumber: "STUVW3456X",
      dob: "10-03-1978",
      mobile: "+91 9876543214",
      creditScore: 680,
      riskCategory: "Medium Risk",
      employmentType: "Business",
      monthlyIncome: 120000,
    },
    existingLoans: [],
    creditAnalysis: {
      monthlyIncome: 200000,
      totalExistingEMI: 0,
      foirPercentage: 0,
      eligibleEMICapacity: 100000,
      riskGrade: "A",
      recommendedLoanAmount: 1000000,
      recommendedTenure: 10,
      interestRate: 10.5,
      creditRemarks:
        "Applicant has good credit history with no existing liabilities. Strong candidate for approval.",
    },
  },
};

export const CREDIT_CHECK_DECISIONS = {
  "LON-2024-001": {
    status: "pending",
    decisionType: "",
    recommendedAmount: 2250000,
    recommendedTenure: 20,
    interestRate: 8.5,
    riskGrade: "B+",
    remarks: "",
    officerName: "Credit Officer Sharma",
    decisionDate: new Date().toISOString().split("T")[0],
  },
  "LON-2024-002": {
    status: "pending",
    decisionType: "",
    recommendedAmount: 400000,
    recommendedTenure: 5,
    interestRate: 12.5,
    riskGrade: "C",
    remarks: "",
    officerName: "",
    decisionDate: "",
  },
  "LON-2024-003": {
    status: "pending",
    decisionType: "",
    recommendedAmount: 1000000,
    recommendedTenure: 10,
    interestRate: 10.5,
    riskGrade: "A",
    remarks: "",
    officerName: "",
    decisionDate: "",
  },
};

export const RECENT_CREDIT_SEARCHES = ["LON-2024-001", "LON-2024-002"];

// Disbursement Management Page Data
export const DISBURSEMENT_PENDING_LOANS = [
  {
    id: "LN-2024-001",
    customer: "Rajesh Kumar",
    amount: 500000,
    approvedDate: "2026-03-05",
    type: "Personal Loan",
    bank: "HDFC Bank",
    acc: "501002345678",
    ifsc: "HDFC0001234",
  },
  {
    id: "LN-2024-002",
    customer: "Priya Sharma",
    amount: 300000,
    approvedDate: "2026-03-08",
    type: "Personal Loan",
    bank: "SBI",
    acc: "30201234567",
    ifsc: "SBIN0004567",
  },
  {
    id: "LN-2024-005",
    customer: "Vikram Singh",
    amount: 600000,
    approvedDate: "2026-03-01",
    type: "Personal Loan",
    bank: "Axis Bank",
    acc: "555566667777",
    ifsc: "UTIB0001234",
  },
];

export const DISBURSEMENT_APPROVED_DVS = [
  {
    dvNo: "DV-1001",
    loanId: "LN-2024-010",
    customer: "Amit Kumar",
    amount: 400000,
    status: "approved",
    date: "2026-03-09",
    bank: "Axis Bank",
    mode: "NEFT",
    acc: "444455556666",
    ifsc: "UTIB0005678",
    type: "Business Loan",
  },
  {
    dvNo: "DV-1002",
    loanId: "LN-2024-011",
    customer: "Sneha Gupta",
    amount: 250000,
    status: "approved",
    date: "2026-03-08",
    bank: "Kotak Bank",
    mode: "IMPS",
    acc: "888899990000",
    ifsc: "KKBK0005678",
    type: "Education Loan",
  },
];

export const DISBURSEMENT_PAID_DVS = [
  {
    dvNo: "DV-0999",
    loanId: "LN-2024-008",
    customer: "Rahul Verma",
    amount: 500000,
    status: "paid",
    date: "2026-03-07",
    bank: "HDFC Bank",
    mode: "RTGS",
    acc: "111222333444",
    ifsc: "HDFC0008888",
    type: "Home Loan",
  },
  {
    dvNo: "DV-1003",
    loanId: "LN-2024-009",
    customer: "Ravi Sharma",
    amount: 350000,
    status: "paid",
    date: "2026-03-06",
    bank: "ICICI Bank",
    mode: "NEFT",
    acc: "777788889999",
    ifsc: "ICIC0001234",
    type: "Personal Loan",
  },
];

// EMI Management Page Data
export const EMI_APPROVED_LOANS = [
  {
    id: "LA-EMI-001",
    loanNumber: "LON-2026-001",
    applicantName: "Rajesh Kumar",
    tenureMonths: 24,
    interestRate: 10.5,
    approvedAmount: 500000,
    applicationStatus: "APPROVED",
    approvedDate: "2026-03-05",
  },
  {
    id: "LA-EMI-002",
    loanNumber: "LON-2026-002",
    applicantName: "Vikram Singh",
    tenureMonths: 24,
    interestRate: 10.0,
    approvedAmount: 600000,
    applicationStatus: "APPROVED",
    approvedDate: "2026-03-01",
  },
  {
    id: "LA-EMI-003",
    loanNumber: "LON-2026-003",
    applicantName: "Amit Patel",
    tenureMonths: 36,
    interestRate: 9.5,
    approvedAmount: 750000,
    applicationStatus: "APPROVED",
    approvedDate: "2026-03-07",
  },
];

export const EMI_VOUCHERS = [
  {
    id: "EMV-001",
    voucherNo: "EMV-2026-001",
    loanNumber: "LON-2026-001",
    customerName: "Rajesh Kumar",
    tenure: 24,
    interestRate: 10.5,
    amount: 500000,
    paidAmount: 23150,
    status: "ACTIVE",
    startDate: "2026-03-10",
  },
  {
    id: "EMV-002",
    voucherNo: "EMV-2026-002",
    loanNumber: "LON-2026-002",
    customerName: "Vikram Singh",
    tenure: 24,
    interestRate: 10.0,
    amount: 600000,
    paidAmount: 27640,
    status: "ACTIVE",
    startDate: "2026-03-05",
  },
  {
    id: "EMV-003",
    voucherNo: "EMV-2026-003",
    loanNumber: "LON-2026-003",
    customerName: "Amit Patel",
    tenure: 36,
    interestRate: 9.5,
    amount: 750000,
    paidAmount: 0,
    status: "PENDING",
    startDate: "2026-03-11",
  },
];

// Document Page Defaults (fallback values for API-driven docs)
export const DOCUMENT_PAGE_DEFAULTS = {
  status: "PENDING",
  uploadDate: "-",
  applicantType: "APPLICANT",
};

// Document Verification Page Data
export const DOCUMENT_APPLICATIONS = [
  {
    id: "DOC-001",
    loanNumber: "LON-2024-1001",
    applicationNumber: "APP-2024-1001",
    applicantName: "Rajesh Kumar",
    coApplicantName: "Priya Kumar",
    loanAmount: 2500000,
    currentStage: "Document Verification",
    totalDocuments: 8,
  },
  {
    id: "DOC-002",
    loanNumber: "LON-2024-1002",
    applicationNumber: "APP-2024-1002",
    applicantName: "Amit Sharma",
    coApplicantName: null,
    loanAmount: 500000,
    currentStage: "Document Verification",
    totalDocuments: 6,
  },
  {
    id: "DOC-003",
    loanNumber: "LON-2024-1003",
    applicationNumber: "APP-2024-1003",
    applicantName: "Sunita Patel",
    coApplicantName: "Rahul Patel",
    loanAmount: 1000000,
    currentStage: "Document Verification",
    totalDocuments: 10,
  },
  {
    id: "DOC-004",
    loanNumber: "LON-2024-1004",
    applicationNumber: "APP-2024-1004",
    applicantName: "Vikram Singh",
    coApplicantName: null,
    loanAmount: 750000,
    currentStage: "Document Verification",
    totalDocuments: 7,
  },
  {
    id: "DOC-005",
    loanNumber: "LON-2024-1005",
    applicationNumber: "APP-2024-1005",
    applicantName: "Sneha Desai",
    coApplicantName: "Karan Desai",
    loanAmount: 1200000,
    currentStage: "Document Verification",
    totalDocuments: 9,
  },
];

export const DOCUMENT_REPOSITORY = {
  "DOC-001": [
    {
      id: 1,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_rajesh.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-05",
    },
    {
      id: 2,
      name: "PAN Card",
      url: "/uploads/pan_rajesh.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-05",
    },
    {
      id: 3,
      name: "Salary Slip",
      url: "/uploads/salary_rajesh.pdf",
      status: "PENDING",
      category: "income_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-06",
    },
    {
      id: 4,
      name: "Bank Statement",
      url: "/uploads/bank_rajesh.pdf",
      status: "VERIFIED",
      category: "bank_statement",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-06",
    },
    {
      id: 5,
      name: "Address Proof",
      url: "/uploads/address_rajesh.pdf",
      status: "VERIFIED",
      category: "address_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-07",
    },
    {
      id: 6,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_priya.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-07",
    },
    {
      id: 7,
      name: "PAN Card",
      url: "/uploads/pan_priya.pdf",
      status: "PENDING",
      category: "identity_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-08",
    },
    {
      id: 8,
      name: "Income Tax Return",
      url: "/uploads/itr_priya.pdf",
      status: "VERIFIED",
      category: "income_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-08",
    },
  ],
  "DOC-002": [
    {
      id: 1,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_amit.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-04",
    },
    {
      id: 2,
      name: "PAN Card",
      url: "/uploads/pan_amit.pdf",
      status: "REJECTED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-04",
    },
    {
      id: 3,
      name: "Salary Slip",
      url: "/uploads/salary_amit.pdf",
      status: "VERIFIED",
      category: "income_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-05",
    },
    {
      id: 4,
      name: "Bank Statement",
      url: "/uploads/bank_amit.pdf",
      status: "PENDING",
      category: "bank_statement",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-06",
    },
  ],
  "DOC-003": [
    {
      id: 1,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_sunita.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-03",
    },
    {
      id: 2,
      name: "PAN Card",
      url: "/uploads/pan_sunita.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-03",
    },
    {
      id: 3,
      name: "Business Proof",
      url: "/uploads/business_sunita.pdf",
      status: "VERIFIED",
      category: "business_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-04",
    },
    {
      id: 4,
      name: "GST Certificate",
      url: "/uploads/gst_sunita.pdf",
      status: "PENDING",
      category: "business_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-04",
    },
    {
      id: 5,
      name: "Bank Statement",
      url: "/uploads/bank_sunita.pdf",
      status: "VERIFIED",
      category: "bank_statement",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-05",
    },
    {
      id: 6,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_rahul.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-05",
    },
    {
      id: 7,
      name: "PAN Card",
      url: "/uploads/pan_rahul.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-06",
    },
    {
      id: 8,
      name: "Business Proof",
      url: "/uploads/business_rahul.pdf",
      status: "PENDING",
      category: "business_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-06",
    },
  ],
  "DOC-004": [
    {
      id: 1,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_vikram.pdf",
      status: "PENDING",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-08",
    },
    {
      id: 2,
      name: "PAN Card",
      url: "/uploads/pan_vikram.pdf",
      status: "PENDING",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-08",
    },
    {
      id: 3,
      name: "Salary Slip",
      url: "/uploads/salary_vikram.pdf",
      status: "PENDING",
      category: "income_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-09",
    },
  ],
  "DOC-005": [
    {
      id: 1,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_sneha.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-02",
    },
    {
      id: 2,
      name: "PAN Card",
      url: "/uploads/pan_sneha.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-02",
    },
    {
      id: 3,
      name: "Property Documents",
      url: "/uploads/property_sneha.pdf",
      status: "VERIFIED",
      category: "property_documents",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-03",
    },
    {
      id: 4,
      name: "Bank Statement",
      url: "/uploads/bank_sneha.pdf",
      status: "VERIFIED",
      category: "bank_statement",
      applicantType: "APPLICANT",
      uploadDate: "2026-03-04",
    },
    {
      id: 5,
      name: "Aadhaar Card",
      url: "/uploads/aadhaar_karan.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-04",
    },
    {
      id: 6,
      name: "PAN Card",
      url: "/uploads/pan_karan.pdf",
      status: "VERIFIED",
      category: "identity_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-05",
    },
    {
      id: 7,
      name: "Salary Slip",
      url: "/uploads/salary_karan.pdf",
      status: "VERIFIED",
      category: "income_proof",
      applicantType: "CO_APPLICANT",
      uploadDate: "2026-03-06",
    },
  ],
};
