export const LEADS_PAGE_DUMMY_CONFIG = {
  ITEMS_PER_PAGE: 6,
  MAX_VISIBLE_PAGES: 5,
};

export const LEAD_ACTION_DEFINITIONS = [
  {
    key: "edit",
    label: "Edit",
    icon: "Edit",
  },
  {
    key: "delete",
    label: "Delete",
    icon: "Trash2",
    isDanger: true,
  },
];

export const LEADS_DUMMY_DATA = [
  {
    id: "lead-1",
    leadNumber: "LD0001",
    fullName: "Rahul Sharma",
    contactNumber: "9876543210",
    email: "rahul.sharma@gmail.com",
    city: "Jaipur",
    state: "Rajasthan",
    loanAmount: 300000,
    loanType: { name: "Home Loan" },
    createdAt: "2026-03-10T09:30:00.000Z",
  },
  {
    id: "lead-2",
    leadNumber: "LD0002",
    fullName: "Priya Singh",
    contactNumber: "9988776655",
    email: "priya.singh@gmail.com",
    city: "Delhi",
    state: "Delhi",
    loanAmount: 500000,
    loanType: { name: "Personal Loan" },
    createdAt: "2026-03-09T14:45:00.000Z",
  },
  {
    id: "lead-3",
    leadNumber: "LD0003",
    fullName: "Amit Verma",
    contactNumber: "9123456789",
    email: "amit.verma@gmail.com",
    city: "Mumbai",
    state: "Maharashtra",
    loanAmount: 1200000,
    loanType: { name: "Business Loan" },
    createdAt: "2026-03-08T11:20:00.000Z",
  },
  {
    id: "lead-4",
    leadNumber: "LD0004",
    fullName: "Sneha Patel",
    contactNumber: "9012345678",
    email: "sneha.patel@gmail.com",
    city: "Ahmedabad",
    state: "Gujarat",
    loanAmount: 800000,
    loanType: { name: "Car Loan" },
    createdAt: "2026-03-07T16:00:00.000Z",
  },
  {
    id: "lead-5",
    leadNumber: "LD0005",
    fullName: "Mohit Gupta",
    contactNumber: "9098765432",
    email: "mohit.gupta@gmail.com",
    city: "Lucknow",
    state: "Uttar Pradesh",
    loanAmount: 250000,
    loanType: { name: "Education Loan" },
    createdAt: "2026-03-06T10:15:00.000Z",
  },
];

export const getLeadLoanTypeColor = (name = "") => {
  const key = name.toLowerCase();

  if (key.includes("home")) return "bg-blue-50 text-blue-700 border-blue-200";
  if (key.includes("personal"))
    return "bg-purple-50 text-purple-700 border-purple-200";
  if (key.includes("car")) return "bg-green-50 text-green-700 border-green-200";
  if (key.includes("business"))
    return "bg-amber-50 text-amber-700 border-amber-200";
  if (key.includes("education"))
    return "bg-indigo-50 text-indigo-700 border-indigo-200";

  return "bg-gray-50 text-gray-700 border-gray-200";
};

// Due List Page Dummy Data
export const DUE_LIST_ITEMS_PER_PAGE = 10;

export const DUE_LIST_DEFAULT_FILTERS = {
  type: "All Types",
  branch: "All Branches",
  product: "All Products",
  bucketSlab: "All Slabs",
  executive: "All Executives",
  source: "All Sources",
  dueUpTo: "",
  withLPI: false,
  assignmentStatus: "All",
};

export const DUE_LIST_COLLECTION_EXECUTIVES = [
  {
    id: 1,
    name: "John Doe",
    email: "john@loan.com",
    phone: "+91 98765 43210",
    currentLoad: 15,
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@loan.com",
    phone: "+91 98765 43211",
    currentLoad: 12,
  },
  {
    id: 3,
    name: "Robert Johnson",
    email: "robert@loan.com",
    phone: "+91 98765 43212",
    currentLoad: 18,
  },
  {
    id: 4,
    name: "Sarah Williams",
    email: "sarah@loan.com",
    phone: "+91 98765 43213",
    currentLoad: 10,
  },
];

export const DUE_LIST_FILTER_OPTIONS = {
  loanTypes: [
    "All Types",
    "OD Cases",
    "Regular Due",
    "Closed Loans",
    "Active Loans",
  ],
  branches: [
    "All Branches",
    "Delhi Main",
    "Mumbai West",
    "Bangalore South",
    "Chennai Central",
  ],
  products: [
    "All Products",
    "Personal Loan",
    "Business Loan",
    "Home Loan",
    "Vehicle Loan",
  ],
  bucketSlabs: [
    "All Slabs",
    "0–30 days",
    "31–60 days",
    "61–90 days",
    "90+ days",
  ],
  executives: [
    "All Executives",
    "John Doe",
    "Jane Smith",
    "Robert Johnson",
    "Sarah Williams",
  ],
  sources: ["All Sources", "Agent", "Direct", "Online Lead", "Partner"],
  assignmentStatus: ["All", "Assigned", "Unassigned", "Pending"],
};

export const DUE_LIST_SUMMARY_CARD_CONFIG = [
  {
    title: "Total Due Amount",
    change: "+12.5%",
    trend: "up",
    iconName: "DollarSign",
    color: "border-l-blue-500 bg-blue-50",
    iconColor: "text-blue-600",
  },
  {
    title: "Total Accounts",
    change: "+8",
    trend: "up",
    iconName: "Users",
    color: "border-l-green-500 bg-green-50",
    iconColor: "text-green-600",
  },
  {
    title: "Critical Overdue",
    change: "-3",
    trend: "down",
    iconName: "AlertTriangle",
    color: "border-l-red-500 bg-red-50",
    iconColor: "text-red-600",
  },
  {
    title: "Assigned Tasks",
    change: "+5 Today",
    trend: "up",
    iconName: "ClipboardCheck",
    color: "border-l-purple-500 bg-purple-50",
    iconColor: "text-purple-600",
  },
];

export const DUE_LIST_INITIAL_DATA = [
  {
    id: "LN1001",
    customerName: "Rahul Sharma",
    loanNumber: "L-2024-001",
    emiAmount: 25000,
    dueDate: "2024-03-10",
    overdueDays: 5,
    lpiAmount: 1250,
    totalDue: 26250,
    branch: "Delhi Main",
    product: "Personal Loan",
    collectionExecutive: "",
    contact: "+91 9876543210",
    status: "Due",
    type: "Regular Due",
    source: "Direct",
    bucketSlab: "0–30 days",
    lastContacted: "2024-03-05",
    assignmentStatus: "Unassigned",
  },
  {
    id: "LN1002",
    customerName: "Priya Patel",
    loanNumber: "L-2024-002",
    emiAmount: 45000,
    dueDate: "2024-02-28",
    overdueDays: 15,
    lpiAmount: 6750,
    totalDue: 51750,
    branch: "Mumbai West",
    product: "Business Loan",
    collectionExecutive: "John Doe",
    contact: "+91 9876543211",
    status: "Overdue",
    type: "OD Cases",
    source: "Agent",
    bucketSlab: "31–60 days",
    lastContacted: "2024-03-01",
    assignmentStatus: "Assigned",
  },
  {
    id: "LN1003",
    customerName: "Amit Verma",
    loanNumber: "L-2024-003",
    emiAmount: 18000,
    dueDate: "2024-01-15",
    overdueDays: 55,
    lpiAmount: 9900,
    totalDue: 27900,
    branch: "Bangalore South",
    product: "Vehicle Loan",
    collectionExecutive: "Jane Smith",
    contact: "+91 9876543212",
    status: "Critical",
    type: "OD Cases",
    source: "Online Lead",
    bucketSlab: "61–90 days",
    lastContacted: "2024-02-20",
    assignmentStatus: "Assigned",
  },
  {
    id: "LN1004",
    customerName: "Sonia Kapoor",
    loanNumber: "L-2024-004",
    emiAmount: 75000,
    dueDate: "2023-11-30",
    overdueDays: 120,
    lpiAmount: 45000,
    totalDue: 120000,
    branch: "Chennai Central",
    product: "Home Loan",
    collectionExecutive: "Robert Johnson",
    contact: "+91 9876543213",
    status: "Critical",
    type: "OD Cases",
    source: "Partner",
    bucketSlab: "90+ days",
    lastContacted: "2024-01-10",
    assignmentStatus: "Assigned",
  },
  {
    id: "LN1005",
    customerName: "Rajesh Kumar",
    loanNumber: "L-2024-005",
    emiAmount: 32000,
    dueDate: "2024-03-15",
    overdueDays: 0,
    lpiAmount: 0,
    totalDue: 32000,
    branch: "Delhi Main",
    product: "Personal Loan",
    collectionExecutive: "",
    contact: "+91 9876543214",
    status: "Due",
    type: "Regular Due",
    source: "Direct",
    bucketSlab: "0–30 days",
    lastContacted: "2024-03-10",
    assignmentStatus: "Unassigned",
  },
];

// Disbursement & Collection Dashboard Dummy Data

export const DISBURS_COLLECTION_PERFORMANCE_DATA = {
  totalDisbursed: 12500000,
  totalCollected: 9500000,
  collectionRatio: 76,
  pendingDisbursements: 15,
  activeLoans: 280,
  averageTicketSize: 425000,
  npaRate: 2.8,
  recoveryRate: 85,
};

export const DISBURS_COLLECTION_COMPARISON_DATA = {
  months: [
    { name: "Jan", disbursed: 10500000, collected: 8200000 },
    { name: "Feb", disbursed: 9800000, collected: 7500000 },
    { name: "Mar", disbursed: 11200000, collected: 8500000 },
    { name: "Apr", disbursed: 12500000, collected: 9500000 },
    { name: "May", disbursed: 11800000, collected: 8900000 },
    { name: "Jun", disbursed: 13500000, collected: 10200000 },
  ],
};

export const DISBURS_COLLECTION_PRODUCTS_DATA = [
  {
    name: "Personal Loan",
    loans: 125,
    disbursed: 42500000,
    collected: 32500000,
    ratio: 76,
  },
  {
    name: "Business Loan",
    loans: 68,
    disbursed: 85000000,
    collected: 62000000,
    ratio: 73,
  },
  {
    name: "Home Loan",
    loans: 45,
    disbursed: 220000000,
    collected: 175000000,
    ratio: 79,
  },
  {
    name: "Vehicle Loan",
    loans: 42,
    disbursed: 18500000,
    collected: 14800000,
    ratio: 80,
  },
];

export const DISBURS_COLLECTION_BRANCHES_DATA = [
  {
    name: "Delhi Main",
    manager: "Rahul Sharma",
    disbursed: 45000000,
    collected: 36000000,
    ratio: 80,
    performance: "Excellent",
  },
  {
    name: "Mumbai West",
    manager: "Priya Patel",
    disbursed: 38000000,
    collected: 28500000,
    ratio: 75,
    performance: "Good",
  },
  {
    name: "Bangalore South",
    manager: "Amit Verma",
    disbursed: 32000000,
    collected: 22400000,
    ratio: 70,
    performance: "Average",
  },
  {
    name: "Chennai Central",
    manager: "Sonia Kapoor",
    disbursed: 28000000,
    collected: 19600000,
    ratio: 70,
    performance: "Average",
  },
  {
    name: "Hyderabad North",
    manager: "Rajesh Kumar",
    disbursed: 22000000,
    collected: 17600000,
    ratio: 80,
    performance: "Excellent",
  },
];

export const DISBURS_COLLECTION_RECENT_DISBURSEMENTS = [
  {
    customer: "Rahul Sharma",
    loanNumber: "LN-2024-001",
    product: "Personal Loan",
    amount: 500000,
    date: "2024-03-15",
    branch: "Delhi Main",
    officer: "John Doe",
  },
  {
    customer: "Priya Patel",
    loanNumber: "LN-2024-002",
    product: "Business Loan",
    amount: 1500000,
    date: "2024-03-14",
    branch: "Mumbai West",
    officer: "Jane Smith",
  },
  {
    customer: "Amit Verma",
    loanNumber: "LN-2024-003",
    product: "Home Loan",
    amount: 3500000,
    date: "2024-03-12",
    branch: "Bangalore South",
    officer: "Robert Johnson",
  },
  {
    customer: "Sonia Kapoor",
    loanNumber: "LN-2024-004",
    product: "Vehicle Loan",
    amount: 800000,
    date: "2024-03-10",
    branch: "Chennai Central",
    officer: "Sarah Williams",
  },
  {
    customer: "Rajesh Kumar",
    loanNumber: "LN-2024-005",
    product: "Personal Loan",
    amount: 600000,
    date: "2024-03-08",
    branch: "Hyderabad North",
    officer: "John Doe",
  },
];

export const DISBURS_COLLECTION_TOP_COLLECTORS = [
  {
    name: "John Doe",
    branch: "Delhi Main",
    assigned: 45,
    collected: 2850000,
    performance: 95,
  },
  {
    name: "Jane Smith",
    branch: "Mumbai West",
    assigned: 38,
    collected: 2450000,
    performance: 92,
  },
  {
    name: "Robert Johnson",
    branch: "Bangalore South",
    assigned: 42,
    collected: 2250000,
    performance: 88,
  },
  {
    name: "Sarah Williams",
    branch: "Chennai Central",
    assigned: 35,
    collected: 1980000,
    performance: 85,
  },
  {
    name: "Michael Brown",
    branch: "Hyderabad North",
    assigned: 28,
    collected: 1650000,
    performance: 82,
  },
];

export const DISBURS_COLLECTION_PERFORMANCE_CARD_CONFIG = [
  {
    title: "Total Disbursed",
    valueKey: "totalDisbursed",
    valueFormat: "currency",
    change: "+15.2%",
    trend: "up",
    iconName: "TrendingUp",
    color: "border-l-blue-500",
  },
  {
    title: "Total Collected",
    valueKey: "totalCollected",
    valueFormat: "currency",
    change: "+12.8%",
    trend: "up",
    iconName: "Banknote",
    color: "border-l-green-500",
  },
  {
    title: "Collection Ratio",
    valueKey: "collectionRatio",
    valueSuffix: "%",
    change: "+3.2%",
    trend: "up",
    iconName: "Percent",
    color: "border-l-purple-500",
  },
  {
    title: "Active Loans",
    valueKey: "activeLoans",
    valueFormat: "number",
    change: "+8",
    trend: "up",
    iconName: "Users",
    color: "border-l-orange-500",
  },
];

export const DISBURS_COLLECTION_SECONDARY_PERFORMANCE_CARD_CONFIG = [
  {
    title: "Average Ticket Size",
    valueKey: "averageTicketSize",
    valueFormat: "currency",
    change: "+5.4%",
    trend: "up",
    iconName: "DollarSign",
    color: "border-l-indigo-500",
  },
  {
    title: "NPA Rate",
    valueKey: "npaRate",
    valueSuffix: "%",
    change: "-0.3%",
    trend: "down",
    iconName: "AlertCircle",
    color: "border-l-red-500",
  },
  {
    title: "Recovery Rate",
    valueKey: "recoveryRate",
    valueSuffix: "%",
    change: "+2.1%",
    trend: "up",
    iconName: "Target",
    color: "border-l-teal-500",
  },
  {
    title: "Pending Disbursements",
    valueKey: "pendingDisbursements",
    change: "-3",
    trend: "down",
    iconName: "Clock",
    color: "border-l-yellow-500",
  },
];

export const DISBURS_COLLECTION_FINANCIAL_SUMMARY = [
  {
    title: "Net Disbursement",
    description: "Disbursed minus Collected",
    iconName: "DollarSign",
    backgroundClass: "bg-blue-50",
    iconColorClass: "text-blue-600",
    valueType: "netDisbursement",
  },
  {
    title: "Growth Rate",
    description: "YoY Collection Growth",
    iconName: "TrendingUp",
    backgroundClass: "bg-green-50",
    iconColorClass: "text-green-600",
    value: "18.5%",
  },
  {
    title: "Target Achievement",
    description: "Against Quarterly Target",
    iconName: "Target",
    backgroundClass: "bg-purple-50",
    iconColorClass: "text-purple-600",
    value: "94%",
  },
  {
    title: "Next Milestone",
    description: "Monthly Collection Target",
    iconName: "Calendar",
    backgroundClass: "bg-orange-50",
    iconColorClass: "text-orange-600",
    value: "₹15 Cr",
  },
];

// Customer & Booking List Page Dummy Data
export const BOOKING_LIST_DUMMY_DATA = [
  {
    id: "APP-2024-001",
    customerName: "Rahul Sharma",
    mobile: "+91 9876543210",
    loanAmount: 500000,
    product: "Personal Loan",
    branch: "Delhi Main",
    applicationDate: "2024-03-15",
    status: "Pending",
    assignedExecutive: "John Doe",
    source: "Online",
  },
  {
    id: "APP-2024-002",
    customerName: "Priya Patel",
    mobile: "+91 9876543211",
    loanAmount: 1500000,
    product: "Business Loan",
    branch: "Mumbai West",
    applicationDate: "2024-03-14",
    status: "Approved",
    assignedExecutive: "Jane Smith",
    source: "Agent",
  },
  {
    id: "APP-2024-003",
    customerName: "Amit Verma",
    mobile: "+91 9876543212",
    loanAmount: 3500000,
    product: "Home Loan",
    branch: "Bangalore South",
    applicationDate: "2024-03-12",
    status: "Disbursed",
    assignedExecutive: "Robert Johnson",
    source: "Walk-in",
  },
  {
    id: "APP-2024-004",
    customerName: "Sonia Kapoor",
    mobile: "+91 9876543213",
    loanAmount: 800000,
    product: "Vehicle Loan",
    branch: "Chennai Central",
    applicationDate: "2024-03-10",
    status: "Rejected",
    assignedExecutive: "Sarah Williams",
    source: "Partner",
  },
  {
    id: "APP-2024-005",
    customerName: "Rajesh Kumar",
    mobile: "+91 9876543214",
    loanAmount: 1200000,
    product: "Personal Loan",
    branch: "Delhi Main",
    applicationDate: "2024-03-08",
    status: "Pending",
    assignedExecutive: "John Doe",
    source: "Online",
  },
  {
    id: "APP-2024-006",
    customerName: "Neha Singh",
    mobile: "+91 9876543215",
    loanAmount: 2500000,
    product: "Business Loan",
    branch: "Mumbai West",
    applicationDate: "2024-03-07",
    status: "Approved",
    assignedExecutive: "Jane Smith",
    source: "Agent",
  },
  {
    id: "APP-2024-007",
    customerName: "Vikram Yadav",
    mobile: "+91 9876543216",
    loanAmount: 1800000,
    product: "Home Loan",
    branch: "Bangalore South",
    applicationDate: "2024-03-05",
    status: "Disbursed",
    assignedExecutive: "Robert Johnson",
    source: "Walk-in",
  },
  {
    id: "APP-2024-008",
    customerName: "Anjali Reddy",
    mobile: "+91 9876543217",
    loanAmount: 600000,
    product: "Vehicle Loan",
    branch: "Chennai Central",
    applicationDate: "2024-03-03",
    status: "Pending",
    assignedExecutive: "Sarah Williams",
    source: "Partner",
  },
];

export const CUSTOMER_LIST_DUMMY_DATA = [
  {
    customerId: "CUST-1001",
    loanAccount: "L-2023-001",
    customerName: "Rahul Sharma",
    mobile: "+91 9876543210",
    disbursedAmount: 500000,
    emiAmount: 12500,
    outstandingBalance: 425000,
    dueDate: "2024-04-05",
    loanStatus: "Active",
    collectionExecutive: "Mike Wilson",
    emiStatus: "Regular",
  },
  {
    customerId: "CUST-1002",
    loanAccount: "L-2023-002",
    customerName: "Priya Patel",
    mobile: "+91 9876543211",
    disbursedAmount: 1500000,
    emiAmount: 37500,
    outstandingBalance: 1350000,
    dueDate: "2024-04-10",
    loanStatus: "Active",
    collectionExecutive: "Lisa Brown",
    emiStatus: "Late",
  },
  {
    customerId: "CUST-1003",
    loanAccount: "L-2023-003",
    customerName: "Amit Verma",
    mobile: "+91 9876543212",
    disbursedAmount: 3500000,
    emiAmount: 87500,
    outstandingBalance: 3150000,
    dueDate: "2024-04-15",
    loanStatus: "Active",
    collectionExecutive: "Mike Wilson",
    emiStatus: "Regular",
  },
  {
    customerId: "CUST-1004",
    loanAccount: "L-2022-001",
    customerName: "Sonia Kapoor",
    mobile: "+91 9876543213",
    disbursedAmount: 800000,
    emiAmount: 20000,
    outstandingBalance: 0,
    dueDate: "2023-12-05",
    loanStatus: "Closed",
    collectionExecutive: "Lisa Brown",
    emiStatus: "Regular",
  },
  {
    customerId: "CUST-1005",
    loanAccount: "L-2023-004",
    customerName: "Rajesh Kumar",
    mobile: "+91 9876543214",
    disbursedAmount: 1200000,
    emiAmount: 30000,
    outstandingBalance: 1080000,
    dueDate: "2024-03-25",
    loanStatus: "Overdue",
    collectionExecutive: "Mike Wilson",
    emiStatus: "Late",
  },
  {
    customerId: "CUST-1006",
    loanAccount: "L-2023-005",
    customerName: "Neha Singh",
    mobile: "+91 9876543215",
    disbursedAmount: 2500000,
    emiAmount: 62500,
    outstandingBalance: 2250000,
    dueDate: "2024-04-20",
    loanStatus: "Active",
    collectionExecutive: "Lisa Brown",
    emiStatus: "Regular",
  },
  {
    customerId: "CUST-1007",
    loanAccount: "L-2023-006",
    customerName: "Vikram Yadav",
    mobile: "+91 9876543216",
    disbursedAmount: 1800000,
    emiAmount: 45000,
    outstandingBalance: 1620000,
    dueDate: "2024-04-12",
    loanStatus: "Active",
    collectionExecutive: "Mike Wilson",
    emiStatus: "Regular",
  },
  {
    customerId: "CUST-1008",
    loanAccount: "L-2022-002",
    customerName: "Anjali Reddy",
    mobile: "+91 9876543217",
    disbursedAmount: 600000,
    emiAmount: 15000,
    outstandingBalance: 0,
    dueDate: "2023-11-15",
    loanStatus: "Closed",
    collectionExecutive: "Lisa Brown",
    emiStatus: "Regular",
  },
];

// Sales Target & Achievement Page Dummy Data
export const SALES_TARGET_METRICS = [
  { id: "all", label: "All Metrics" },
  { id: "target", label: "Target" },
  { id: "achieved", label: "Achieved" },
  { id: "performance", label: "Performance" },
];

export const SALES_TARGET_KPI_DATA = [
  {
    title: "Total Target",
    value: "Rs 2.00 Cr",
    change: "+5.2%",
    isPositive: true,
    iconName: "Target",
    iconColor: "text-blue-600",
    color: "blue",
    subtitle: "Monthly Target",
  },
  {
    title: "Achieved",
    value: "Rs 1.45 Cr",
    change: "+12.8%",
    isPositive: true,
    iconName: "TrendingUp",
    iconColor: "text-green-600",
    color: "green",
    subtitle: "Year to Date",
  },
  {
    title: "Performance",
    value: "72.5%",
    change: "-2.1%",
    isPositive: false,
    iconName: "Award",
    iconColor: "text-purple-600",
    color: "purple",
    subtitle: "Vs Previous Month",
  },
  {
    title: "Active Executives",
    value: "25",
    change: "+3",
    isPositive: true,
    iconName: "Users",
    iconColor: "text-orange-600",
    color: "orange",
    subtitle: "On Target",
  },
];

export const SALES_TARGET_BRANCH_OPTIONS = [
  "All",
  "Delhi",
  "Mumbai",
  "Pune",
  "Head Office",
];

export const SALES_TARGET_TOP_PERFORMERS = [
  { name: "Ravi Kumar", progress: 94, target: "Rs50L", achieved: "Rs47L" },
  { name: "Priya Singh", progress: 88, target: "Rs45L", achieved: "Rs39.6L" },
  { name: "Amit Verma", progress: 82, target: "Rs40L", achieved: "Rs32.8L" },
  { name: "Neha Sharma", progress: 78, target: "Rs35L", achieved: "Rs27.3L" },
];

export const SALES_TARGET_PERFORMANCE_TABLE_DATA = [
  {
    name: "Ravi Kumar",
    branch: "Delhi",
    target: "Rs50L",
    achieved: "Rs42L",
    progress: 84,
  },
  {
    name: "Neha Sharma",
    branch: "Mumbai",
    target: "Rs40L",
    achieved: "Rs28L",
    progress: 70,
  },
  {
    name: "Amit Verma",
    branch: "Pune",
    target: "Rs30L",
    achieved: "Rs18L",
    progress: 60,
  },
  {
    name: "Priya Singh",
    branch: "Delhi",
    target: "Rs45L",
    achieved: "Rs39.6L",
    progress: 88,
  },
  {
    name: "Sanjay Patel",
    branch: "Mumbai",
    target: "Rs35L",
    achieved: "Rs24.5L",
    progress: 70,
  },
];

export const SALES_TARGET_CHART_DATA = {
  months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
  targetData: [85, 88, 90, 92, 95, 98],
  achievedData: [70, 72, 75, 78, 80, 82],
};

// NPA Reports Page Dummy Data
export const NPA_REPORTS_DATA = {
  summary: {
    totalPortfolio: 125800000,
    totalNPA: 18500000,
    npaPercentage: 14.7,
    criticalNPACount: 42,
    npaByBucket: [
      { bucket: "30-59 days", amount: 3200000, count: 18, percentage: 17.3 },
      { bucket: "60-89 days", amount: 4500000, count: 24, percentage: 24.3 },
      { bucket: "90-119 days", amount: 5800000, count: 32, percentage: 31.4 },
      { bucket: "120+ days", amount: 5000000, count: 28, percentage: 27.0 },
    ],
    npaByBranch: [
      {
        name: "Main Branch",
        amount: 6500000,
        percentage: 35.1,
        totalLoans: 450,
        npaLoans: 38,
      },
      {
        name: "Downtown",
        amount: 4200000,
        percentage: 22.7,
        totalLoans: 320,
        npaLoans: 24,
      },
      {
        name: "Westside",
        amount: 3800000,
        percentage: 20.5,
        totalLoans: 280,
        npaLoans: 22,
      },
      {
        name: "East End",
        amount: 2500000,
        percentage: 13.5,
        totalLoans: 180,
        npaLoans: 14,
      },
      {
        name: "Northgate",
        amount: 1500000,
        percentage: 8.1,
        totalLoans: 120,
        npaLoans: 8,
      },
    ],
    npaByProduct: [
      { product: "Home Loan", amount: 7200000, percentage: 38.9 },
      { product: "Personal Loan", amount: 5200000, percentage: 28.1 },
      { product: "Business Loan", amount: 3800000, percentage: 20.5 },
      { product: "Auto Loan", amount: 2300000, percentage: 12.4 },
    ],
  },
  details: [
    {
      id: 1,
      customerName: "Rajesh Kumar",
      accountNumber: "LN20240001",
      branch: "Main Branch",
      product: "Home Loan",
      emiAmount: 45230,
      overdueDays: 92,
      outstandingBalance: 1850000,
      lastPaymentDate: "2024-01-15",
      collectionExecutive: "Amit Sharma",
      status: "legal",
      riskLevel: "high",
      remarks: "Legal notice sent. Customer unresponsive.",
      contact: "+91 9876543210",
      email: "rajesh.k@email.com",
      address: "123 MG Road, Bangalore",
      loanDate: "2022-03-15",
      tenure: "20 years",
      interestRate: 8.5,
    },
    {
      id: 2,
      customerName: "Priya Singh",
      accountNumber: "LN20240002",
      branch: "Downtown",
      product: "Personal Loan",
      emiAmount: 15600,
      overdueDays: 45,
      outstandingBalance: 420000,
      lastPaymentDate: "2024-02-28",
      collectionExecutive: "Neha Verma",
      status: "follow-up",
      riskLevel: "medium",
      remarks: "Customer promised payment next week",
      contact: "+91 9876543211",
      email: "priya.s@email.com",
      address: "456 Park Street, Delhi",
      loanDate: "2023-06-10",
      tenure: "5 years",
      interestRate: 12.0,
    },
    {
      id: 3,
      customerName: "Vikram Patel",
      accountNumber: "LN20240003",
      branch: "Westside",
      product: "Business Loan",
      emiAmount: 72300,
      overdueDays: 125,
      outstandingBalance: 2850000,
      lastPaymentDate: "2023-12-10",
      collectionExecutive: "Rohit Mehta",
      status: "settlement",
      riskLevel: "critical",
      remarks: "Settlement proposal under review",
      contact: "+91 9876543212",
      email: "vikram.p@email.com",
      address: "789 Business Park, Mumbai",
      loanDate: "2021-09-22",
      tenure: "10 years",
      interestRate: 10.5,
    },
    {
      id: 4,
      customerName: "Anjali Desai",
      accountNumber: "LN20240004",
      branch: "East End",
      product: "Auto Loan",
      emiAmount: 8900,
      overdueDays: 68,
      outstandingBalance: 185000,
      lastPaymentDate: "2024-02-15",
      collectionExecutive: "Amit Sharma",
      status: "follow-up",
      riskLevel: "medium",
      remarks: "Regular contact maintained",
      contact: "+91 9876543213",
      email: "anjali.d@email.com",
      address: "321 Auto Nagar, Chennai",
      loanDate: "2023-01-20",
      tenure: "7 years",
      interestRate: 9.5,
    },
    {
      id: 5,
      customerName: "Sanjay Gupta",
      accountNumber: "LN20240005",
      branch: "Northgate",
      product: "Home Loan",
      emiAmount: 38400,
      overdueDays: 105,
      outstandingBalance: 1250000,
      lastPaymentDate: "2023-12-28",
      collectionExecutive: "Neha Verma",
      status: "legal",
      riskLevel: "high",
      remarks: "Court case filed",
      contact: "+91 9876543214",
      email: "sanjay.g@email.com",
      address: "654 Lake View, Hyderabad",
      loanDate: "2022-08-15",
      tenure: "15 years",
      interestRate: 8.8,
    },
    {
      id: 6,
      customerName: "Meera Iyer",
      accountNumber: "LN20240006",
      branch: "Main Branch",
      product: "Personal Loan",
      emiAmount: 12300,
      overdueDays: 38,
      outstandingBalance: 315000,
      lastPaymentDate: "2024-03-01",
      collectionExecutive: "Rohit Mehta",
      status: "follow-up",
      riskLevel: "low",
      remarks: "Payment expected soon",
      contact: "+91 9876543215",
      email: "meera.i@email.com",
      address: "987 Mall Road, Pune",
      loanDate: "2023-04-12",
      tenure: "4 years",
      interestRate: 11.5,
    },
  ],
};

export const NPA_USER_ROLES = {
  admin: "admin",
  manager: "manager",
  agent: "collection_agent",
};
