export const PERMISSIONS = [
  // Credit & Risk
  "REFRESH_CREDIT_REPORT",
  "CHECK_ELIGIBILITY",

  // Documents
  "UPLOAD_DOCUMENTS",
  "VERIFY_DOCUMENT",
  "VERIFY_DOCUMENTS",

  // EMI
  "VIEW_EMIS",
  "GENERATE_EMI_SCHEDULE",
  "GENERATE_EMI_AMOUNT",
  "VIEW_EMI_PAYABLE_AMOUNT",
  "EMI_PAID",
  "EDIT_EMI",

  // Loan lifecycle
  "CREATE_LOAN_APPLICATION",
  "ASSIGN_LOAN",
  "UNASSIGN_LOAN",
  "VIEW_ASSIGNED_LOANS",
  "DISBURSE_LOAN",
  "VIEW_LOAN_APPLICATIONS",
  "VIEW_LOAN_APPLICATION",
  "UPDATE_LOAN_STATUS",
  "REVIEW_LOAN",
  "APPROVE_LOAN",
  "REJECT_LOAN",

  // Defaults & Recoveries
  "CHECK_LOAN_DEFAULT",
  "VIEW_DEFAULTED_LOANS",
  "VIEW_LOAN_RECOVERIES",
  "VIEW_LOAN_RECOVERY_DETAILS",
  "PAY_RECOVERY_AMOUNT",
  "ASSIGN_RECOVERY_AGENT",
  "UPDATE_RECOVERY_STAGE",
  "VIEW_ALL_RECOVERIES",
  "VIEW_RECOVERY_DETAILS",
  "VIEW_AGENT_RECOVERIES",
  "VIEW_RECOVERY_DASHBOARD",

  // Foreclosure & Moratorium
  "VIEW_FORECLOSE_AMOUNT",
  "FORECLOSE_LOAN",
  "APPLY_MORATORIUM",

  // Leads
  "VIEW_ALL_LEADS",
  "VIEW_LEAD_DETAILS",
  "UPDATE_LEAD_STATUS",
  "ASSIGN_LEAD",
  "CONVERT_LEAD_TO_LOAN",

  // Employees
  "CREATE_EMPLOYEE",
  "VIEW_ALL_EMPLOYEES",
  "VIEW_EMPLOYEE_DETAILS",
  "UPDATE_EMPLOYEE",

  // Branches
  "CREATE_BRANCH",
  "UPDATE_BRANCH",
  "VIEW_BRANCH",
  "DELETE_BRANCH",

  // Partners
  "CREATE_PARTNER",
  "CREATE_CHILD_PARTNER",
  "CREATE_LEAD",
  "VIEW_ALL_PARTNERS",
  "VIEW_PARTNER_DETAILS",
  "UPDATE_PARTNER",

  // Loan Types
  "CREATE_LOAN_TYPE",
  "VIEW_LOAN_TYPES",
  "VIEW_LOAN_TYPE",
  "UPDATE_LOAN_TYPE",
  "DELETE_LOAN_TYPE",

  // Legal & Technical
  "CREATE_LEGAL_REPORT",
  "APPROVE_LEGAL_REPORT",
  "VIEW_LEGAL_REPORTS",
  "CREATE_TECHNICAL_REPORT",
  "APPROVE_TECHNICAL_REPORT",
  "VIEW_TECHNICAL_REPORTS",

  // Settlement
  "SETTLE_LOAN",
  "APPLY_SETTLEMENT",
  "APPROVE_SETTLEMENT",
  "PAY_SETTLEMENT",
  "REJECT_SETTLEMENT",
  "VIEW_SETTLEMENT_PAYABLE_AMOUNT",
  "VIEW_SETTLEMENTS",
  "VIEW_SETTLEMENT_DASHBOARD",

  // Permissions
  "CREATE_PERMISSIONS",
  "ASSIGN_PERMISSIONS",
  "VIEW_USER_PERMISSIONS",
  "VIEW_ALL_PERMISSIONS",

  // KYC
  "VIEW_KYC",
  "VIEW_COAPPLICANTS",

  // NACH
  "CREATE_NACH_MANDATE",
  "ACTIVATE_NACH_MANDATE",
  "SUSPEND_NACH_MANDATE",
  "CANCEL_NACH_MANDATE",
  "VIEW_NACH_MANDATE",

  // User management
  "VIEW_ALL_USERS",
  "VIEW_USER_DETAILS",
  "UPDATE_USER",

  // Monitoring & dashboard
  "VIEW_DASHBOARD",
  "VIEW_SLA_BREACHES",
] as const;

export const PERMISSION_GROUPS = {
  CREDIT_RISK: ["REFRESH_CREDIT_REPORT", "CHECK_ELIGIBILITY"],
  DOCUMENTS: ["UPLOAD_DOCUMENTS", "VERIFY_DOCUMENT", "VERIFY_DOCUMENTS"],
  EMI: [
    "VIEW_EMIS",
    "GENERATE_EMI_SCHEDULE",
    "GENERATE_EMI_AMOUNT",
    "VIEW_EMI_PAYABLE_AMOUNT",
    "EMI_PAID",
    "EDIT_EMI",
  ],
  LOAN_LIFECYCLE: [
    "CREATE_LOAN_APPLICATION",
    "ASSIGN_LOAN",
    "UNASSIGN_LOAN",
    "VIEW_ASSIGNED_LOANS",
    "DISBURSE_LOAN",
    "VIEW_LOAN_APPLICATIONS",
    "VIEW_LOAN_APPLICATION",
    "UPDATE_LOAN_STATUS",
    "REVIEW_LOAN",
    "APPROVE_LOAN",
    "REJECT_LOAN",
  ],
  DEFAULTS_RECOVERIES: [
    "CHECK_LOAN_DEFAULT",
    "VIEW_DEFAULTED_LOANS",
    "VIEW_LOAN_RECOVERIES",
    "VIEW_LOAN_RECOVERY_DETAILS",
    "PAY_RECOVERY_AMOUNT",
    "ASSIGN_RECOVERY_AGENT",
    "UPDATE_RECOVERY_STAGE",
    "VIEW_ALL_RECOVERIES",
    "VIEW_RECOVERY_DETAILS",
    "VIEW_AGENT_RECOVERIES",
    "VIEW_RECOVERY_DASHBOARD",
  ],
  FORECLOSURE_MORATORIUM: [
    "VIEW_FORECLOSE_AMOUNT",
    "FORECLOSE_LOAN",
    "APPLY_MORATORIUM",
  ],
  LEADS: [
    "VIEW_ALL_LEADS",
    "VIEW_LEAD_DETAILS",
    "UPDATE_LEAD_STATUS",
    "ASSIGN_LEAD",
    "CONVERT_LEAD_TO_LOAN",
  ],
  EMPLOYEES: [
    "CREATE_EMPLOYEE",
    "VIEW_ALL_EMPLOYEES",
    "VIEW_EMPLOYEE_DETAILS",
    "UPDATE_EMPLOYEE",
  ],
  BRANCHES: ["CREATE_BRANCH", "UPDATE_BRANCH", "VIEW_BRANCH", "DELETE_BRANCH"],
  PARTNERS: [
    "CREATE_PARTNER",
    "CREATE_CHILD_PARTNER",
    "CREATE_LEAD",
    "VIEW_ALL_PARTNERS",
    "VIEW_PARTNER_DETAILS",
    "UPDATE_PARTNER",
  ],
  LOAN_TYPES: [
    "CREATE_LOAN_TYPE",
    "VIEW_LOAN_TYPES",
    "VIEW_LOAN_TYPE",
    "UPDATE_LOAN_TYPE",
    "DELETE_LOAN_TYPE",
  ],
  LEGAL_TECHNICAL: [
    "CREATE_LEGAL_REPORT",
    "APPROVE_LEGAL_REPORT",
    "VIEW_LEGAL_REPORTS",
    "CREATE_TECHNICAL_REPORT",
    "APPROVE_TECHNICAL_REPORT",
    "VIEW_TECHNICAL_REPORTS",
  ],
  SETTLEMENT: [
    "SETTLE_LOAN",
    "APPLY_SETTLEMENT",
    "APPROVE_SETTLEMENT",
    "PAY_SETTLEMENT",
    "REJECT_SETTLEMENT",
    "VIEW_SETTLEMENT_PAYABLE_AMOUNT",
    "VIEW_SETTLEMENTS",
    "VIEW_SETTLEMENT_DASHBOARD",
  ],
  PERMISSIONS: [
    "CREATE_PERMISSIONS",
    "ASSIGN_PERMISSIONS",
    "VIEW_USER_PERMISSIONS",
    "VIEW_ALL_PERMISSIONS",
  ],
  KYC: ["VIEW_KYC", "VIEW_COAPPLICANTS"],
  NACH: [
    "CREATE_NACH_MANDATE",
    "ACTIVATE_NACH_MANDATE",
    "SUSPEND_NACH_MANDATE",
    "CANCEL_NACH_MANDATE",
    "VIEW_NACH_MANDATE",
  ],
  USER_MANAGEMENT: ["VIEW_ALL_USERS", "VIEW_USER_DETAILS", "UPDATE_USER"],
  MONITORING_DASHBOARD: ["VIEW_DASHBOARD", "VIEW_SLA_BREACHES"],
} as const;

export type PermissionGroupName = keyof typeof PERMISSION_GROUPS;
