export const PERMISSIONS = [
  // Credit & Risk
  "REFRESH_CREDIT_REPORT",
  "CHECK_ELIGIBILITY",

  // Documents
  "UPLOAD_DOCUMENTS",
  "VERIFY_DOCUMENTS",

  // EMI
  "VIEW_EMIS",
  "GENERATE_EMI_SCHEDULE",
  "GENERATE_EMI_AMOUNT",
  "VIEW_EMI_PAYABLE_AMOUNT",
  "EMI_PAID",

  // Loan lifecycle
  "CREATE_LOAN_APPLICATION",
  "VIEW_LOAN_APPLICATIONS",
  "VIEW_LOAN_APPLICATION",
  "UPDATE_LOAN_STATUS",
  "REVIEW_LOAN",
  "APPROVE_LOAN",
  "REJECT_LOAN",

  // Defaults & Recoveries
  "CHECK_LOAN_DEFAULT",
  "VIEW_DEFAULTED_LOANS",
  "VIEW_LOAN_RECOVERIES",
  "VIEW_LOAN_RECOVERY_DETAILS",
  "PAY_RECOVERY_AMOUNT",
  "ASSIGN_RECOVERY_AGENT",
  "UPDATE_RECOVERY_STAGE",

  // Foreclosure & Moratorium
  "VIEW_FORECLOSE_AMOUNT",
  "FORECLOSE_LOAN",
  "APPLY_MORATORIUM",

  // Leads
  "VIEW_ALL_LEADS",
  "VIEW_LEAD_DETAILS",
  "UPDATE_LEAD_STATUS",
  "ASSIGN_LEAD",
  "CONVERT_LEAD_TO_LOAN",

  // Employees
  "CREATE_EMPLOYEE",
  "VIEW_ALL_EMPLOYEES",
  "VIEW_EMPLOYEE_DETAILS",
  "UPDATE_EMPLOYEE",

  // Partners
  "CREATE_PARTNER",
  "VIEW_ALL_PARTNERS",
  "VIEW_PARTNER_DETAILS",
  "UPDATE_PARTNER",

  // Loan Types
  "CREATE_LOAN_TYPE",
  "VIEW_LOAN_TYPES",
  "VIEW_LOAN_TYPE",
  "UPDATE_LOAN_TYPE",
  "DELETE_LOAN_TYPE",

  // Legal & Technical
  "CREATE_LEGAL_REPORT",
  "APPROVE_LEGAL_REPORT",
  "VIEW_LEGAL_REPORTS",
  "CREATE_TECHNICAL_REPORT",
  "APPROVE_TECHNICAL_REPORT",
  "VIEW_TECHNICAL_REPORTS",

  // Settlement
  "SETTLE_LOAN",
  "APPLY_SETTLEMENT",
  "APPROVE_SETTLEMENT",
  "PAY_SETTLEMENT",
  "REJECT_SETTLEMENT",
  "VIEW_SETTLEMENT_PAYABLE_AMOUNT",
  "VIEW_SETTLEMENTS",
  "VIEW_SETTLEMENT_DASHBOARD",

  // Permissions
  "CREATE_PERMISSIONS",
  "ASSIGN_PERMISSIONS",
  "VIEW_USER_PERMISSIONS",
  "VIEW_ALL_PERMISSIONS",
] as const;
