import { Router, Request, Response } from "express";
import userRoutes from "./modules/user/userRoutes/user.routes.js";
import { authRouter } from "./modules/auth/auth.route.js";
import { employeeRouter } from "./modules/employee/employee.routes.js";
import employeeRoleRouter from "./modules/employeeRole/employeeRole.routes.js";
import partnerRouter from "./modules/partner/partner.routes.js";
import { leadRouter } from "./modules/lead/lead.routes.js";
import loanApplicationRouter from "./modules/LoanApplication/loanApplication.routes.js";
import permissionRouter from "./modules/permission/permission.routes.js";
import kycRouter from "./modules/kyc/kyc.routes.js";
import emiRouter from "./modules/emi/emi.router.js";
import forecloseRouter from "./modules/foreclose/foreclose.router.js";
import loanCloseRouter from "./modules/loanClose/loanclose.routes.js";
import loanTypeRouter from "./modules/loanTypes/loanTypes.routes.js";
import jobsRouter from "./jobs/jobs.routes.js";
import recoveryRouter from "./modules/recovery/recovery.routes.js";
import loanSettlementRouter from "./modules/settlement/loanSettlement.routes.js";
import loanDefaultRouter from "./modules/loanDefault/loanDefault.route.js";
import eligibilityRouter from "./modules/loanRuleEngine/ruleEngine.routes.js";
import creditReportRouter from "./modules/creditReport/creditReport.router.js";
import technicalReportRouter from "./modules/reports/technicalReport/technical.routes.js";
import legalReportRouter from "./modules/reports/legalReport/legal.routes.js";
import coApplicantRouter from "./modules/coApplicants/coApplicant.routes.js";
import loanAssignmentRouter from "./modules/loanAssignment/loanAssignment.routes.js";
import branchRouter from "./modules/branch/branch.router.js";
import branchAdminRouter from "./modules/branchAdmin/branchAdmin.router.js";
import slaRouter from "./modules/sla/sla.router.js";
import { superAdminRouter } from "./modules/superAdmin/dashboard.routers.js";
import loanDisbursementRouter from "./modules/loanDisbursement/loanDisburesment.router.js";
import nachRouter from "./modules/nach/nach.router.js";
import guarantorRouter from "./modules/guarantor/guarantor.routes.js";
import loanDraftRouter from "./modules/loanDraft/loanDraft.router.js";
import sanctionRouter from "./modules/sanction/sanction.router.js";
import aadhaarRouter from "./modules/aadhaar/aadhaar.routes.js";
import panRouter from "./modules/pan/pan.routes.js";

const router = Router();

router.get("/", (req: Request, res: Response) => {
  res.send("Welcome to the LMS Backend!");
});
router.use("/user", userRoutes);
router.use("/auth", authRouter);
router.use("/employee", employeeRouter);
router.use("/employee-roles", employeeRoleRouter);
router.use("/partner", partnerRouter);
router.use("/lead", leadRouter);
router.use("/loan-applications", loanApplicationRouter);
router.use("/permissions", permissionRouter);
router.use("/kyc", kycRouter);
router.use("/jobs", jobsRouter);
router.use("/emi", emiRouter);
router.use("/foreclose", forecloseRouter);
router.use("/loan-close", loanCloseRouter);
router.use("/loantypes", loanTypeRouter);
router.use("/recovery", recoveryRouter);
router.use("/settlement", loanSettlementRouter);
router.use("/risk", eligibilityRouter);
router.use("/loan-default", loanDefaultRouter);
router.use("/credit", creditReportRouter);
router.use("/reports/technical", technicalReportRouter);
router.use("/reports/legal", legalReportRouter);
router.use("/co-applicant", coApplicantRouter);
router.use("/loan-assignment", loanAssignmentRouter);
router.use("/branches", branchRouter);
router.use("/branch-admins", branchAdminRouter);
router.use("/sla", slaRouter);
router.use("/super-admin", superAdminRouter);
router.use("/disbursement", loanDisbursementRouter);
router.use("/nach", nachRouter);
router.use("/guarantor", guarantorRouter);
router.use("/loan-drafts", loanDraftRouter);
router.use("/sanctions", sanctionRouter);
router.use("/foreclose", forecloseRouter);
router.use("/aadhaar",aadhaarRouter);
router.use("/pan", panRouter);
export default router;
