// Maps form values to API payload for loan type
export function mapLoanTypeFormToPayload(form) {
  return {
    code: form.loanCode,
    name: form.loanName,
    category: form.loanCategory,
    minAmount: form.minLoanAmount,
    maxAmount: form.maxLoanAmount,
    minTenureMonths: form.minTenure,
    maxTenureMonths: form.maxTenure,
    minInterestRate: form.minInterestRate,
    maxInterestRate: form.maxInterestRate,
    defaultInterestRate: form.defaultInterestRate,
    interestType: form.interestType,
    processingFeeType: form.processingFeeType,
    processingFee: form.processingFeeValue,
    gstApplicable: form.gstApplicable,
    gstPercentage: form.gstPercentage,
    minAge: form.minAge,
    maxAge: form.maxAge,
    secured: form.securedLoan,
    minMonthlyIncome: form.minMonthlyIncome,
    employmentType: form.employmentType,
    minCibilScore: form.minCibilScore,
    maxCibilScore: form.maxCibilScore,
    maxLoanToValueRatio: form.maxLoanToValueRatio,
    prepaymentAllowed: form.prepaymentAllowed,
    foreclosureAllowed: form.foreclosureAllowed,
    prepaymentCharges: form.prepaymentCharges,
    foreclosureCharges: form.foreclosureCharges,
    latePaymentFeeType: form.latePaymentFeeType,
    latePaymentFee: form.latePaymentFee,
    bounceCharges: form.bounceCharges,
    isActive: form.activeStatus,
    isPublic: form.publicVisibility,
    approvalRequired: form.approvalRequired,
    estimatedProcessingTimeDays: form.estimatedProcessingTimeDays,
    applicantDocumentsRequired: form.applicantDocumentsRequired,
    applicantDocumentsOptional: form.applicantDocumentsOptional,
    coApplicantDocumentsRequired: form.coApplicantDocumentsRequired,
    coApplicantDocumentsOptional: form.coApplicantDocumentsOptional,
    guarantorDocumentsRequired: form.guarantorDocumentsRequired,
    guarantorDocumentsOptional: form.guarantorDocumentsOptional,
  };
}
