export const defaultLoanDummyData = [
  {
    id: "loan_1",
    loanNumber: "LN-1001",
    customer: {
      firstName: "Ravi",
      lastName: "Kumar",
      contactNumber: "+91-9876543210",
      panNumber: "ABCDE1234F",
    },
    branchName: "Mumbai Branch",
    loanType: "Gold Loan",
    dpd: 45,
    approvedAmount: 500000,
    loanRecoveries: [
      {
        balanceAmount: 480000,
        recoveredAmount: 20000,
        recoveryStage: "INITIAL_CONTACT",
        recoveryStatus: "ONGOING",
      },
    ],
    assignedTo: "Somesh R.",
    lastPaymentDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    defaultedAt: new Date().toISOString(),
    emiSummary: { total: 36, paid: 18, overdue: 3 },
    notes: [{ by: "SYSTEM", text: "Marked default after 3 overdue EMIs" }],
  },
  {
    id: "loan_2",
    loanNumber: "LN-1002",
    customer: {
      firstName: "Anita",
      lastName: "Shah",
      contactNumber: "+91-9123456780",
      panNumber: "PQRST5678K",
    },
    branchName: "Delhi Branch",
    loanType: "Personal Loan",
    dpd: 120,
    approvedAmount: 200000,
    loanRecoveries: [
      {
        balanceAmount: 185000,
        recoveredAmount: 15000,
        recoveryStage: "FIELD_VISIT",
        recoveryStatus: "ONGOING",
      },
    ],
    assignedTo: "Neha P.",
    lastPaymentDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    defaultedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    emiSummary: { total: 24, paid: 8, overdue: 6 },
    notes: [{ by: "RECOVERY_OFFICER", text: "Customer unreachable on provided number" }],
  },
  {
    id: "loan_3",
    loanNumber: "LN-1003",
    customer: {
      firstName: "Rajesh",
      lastName: "Verma",
      contactNumber: "+91-9988776655",
      panNumber: "LMNOP9876Q",
    },
    branchName: "Bangalore Branch",
    loanType: "Home Loan",
    dpd: 90,
    approvedAmount: 4500000,
    loanRecoveries: [
      {
        balanceAmount: 4250000,
        recoveredAmount: 250000,
        recoveryStage: "LEGAL_NOTICE",
        recoveryStatus: "ONGOING",
      },
    ],
    assignedTo: "Amit K.",
    lastPaymentDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 95).toISOString(),
    defaultedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    emiSummary: { total: 120, paid: 45, overdue: 9 },
    notes: [{ by: "SYSTEM", text: "Legal notice sent" }],
  },
  {
    id: "loan_4",
    loanNumber: "LN-1004",
    customer: {
      firstName: "Priya",
      lastName: "Singh",
      contactNumber: "+91-8877665544",
      panNumber: "GHIJK5678L",
    },
    branchName: "Chennai Branch",
    loanType: "Auto Loan",
    dpd: 30,
    approvedAmount: 750000,
    loanRecoveries: [
      {
        balanceAmount: 720000,
        recoveredAmount: 30000,
        recoveryStage: "NEGOTIATION",
        recoveryStatus: "ONGOING",
      },
    ],
    assignedTo: "Suresh M.",
    lastPaymentDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
    defaultedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    emiSummary: { total: 48, paid: 12, overdue: 3 },
    notes: [],
  },
  {
    id: "loan_5",
    loanNumber: "LN-1005",
    customer: {
      firstName: "Amit",
      lastName: "Patel",
      contactNumber: "+91-7766554433",
      panNumber: "ABCDE4321G",
    },
    branchName: "Ahmedabad Branch",
    loanType: "Business Loan",
    dpd: 180,
    approvedAmount: 1200000,
    loanRecoveries: [
      {
        balanceAmount: 1150000,
        recoveredAmount: 50000,
        recoveryStage: "COURT_CASE",
        recoveryStatus: "STALLED",
      },
    ],
    assignedTo: "Vijay R.",
    lastPaymentDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 200).toISOString(),
    defaultedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    emiSummary: { total: 60, paid: 20, overdue: 18 },
    notes: [{ by: "RECOVERY_OFFICER", text: "Court hearing scheduled" }],
  },
];
