/*
  Warnings:

  - You are about to alter the column `status` on the `loanapplication` table. The data in that column could be lost. The data in that column will be cast from `Enum(EnumId(49))` to `Enum(EnumId(26))`.

*/
-- AlterTable
ALTER TABLE `loanapplication` MODIFY `status` ENUM('LEAD_CREATED', 'LEAD_VERIFICATION', 'APPLICATION_STARTED', 'DOCUMENT_COLLECTION', 'KYC_VERIFICATION', 'CREDIT_BUREAU_CHECK', 'BANK_STATEMENT_ANALYSIS', 'ELIGIBILITY_CHECK', 'UNDERWRITING', 'APPROVED', 'REJECTED', 'SANCTION_LETTER_ISSUED', 'AGREEMENT_SIGNED', 'DISBURSEMENT_INITIATED', 'DISBURSED', 'MOVED_TO_LMS', 'ACTIVE', 'EMI_SCHEDULE_GENERATED', 'EMI_DUE', 'PAYMENT_RECEIVED', 'DELINQUENT', 'COLLECTIONS', 'SETTLED', 'CLOSED', 'WRITTEN_OFF', 'DEFAULTED', 'FORECLOSURE_PENDING') NOT NULL DEFAULT 'APPLICATION_STARTED';
