-- AlterTable
ALTER TABLE `loanrecovery` MODIFY `recoveryStage` ENUM('INITIAL_CONTACT', 'FIELD_VISIT', 'NEGOTIATION', 'LEGAL_ACTION', 'SETTLEMENT_REQUESTED', 'SETTLEMENT_APPROVED', 'SETTLEMENT', 'CLOSED') NOT NULL;
