-- AlterTable
ALTER TABLE `partner` ADD COLUMN `clawbackTerms` VARCHAR(191) NULL,
    ADD COLUMN `digitalApiIntegration` VARCHAR(191) NULL,
    ADD COLUMN `existingLenderRelationships` VARCHAR(191) NULL,
    ADD COLUMN `geographicCoverage` VARCHAR(191) NULL,
    ADD COLUMN `gstPercentage` DOUBLE NULL,
    ADD COLUMN `incentiveSchemes` VARCHAR(191) NULL,
    ADD COLUMN `monthlySourcingVolume` INTEGER NULL,
    ADD COLUMN `natureOfBusinessDetail` VARCHAR(191) NULL,
    ADD COLUMN `officeAddressLine1` VARCHAR(191) NULL,
    ADD COLUMN `officeAddressLine2` VARCHAR(191) NULL,
    ADD COLUMN `officeCity` VARCHAR(191) NULL,
    ADD COLUMN `officeCountry` VARCHAR(191) NULL,
    ADD COLUMN `officePinCode` VARCHAR(191) NULL,
    ADD COLUMN `officeState` VARCHAR(191) NULL,
    ADD COLUMN `officeStrength` INTEGER NULL,
    ADD COLUMN `productExpertise` VARCHAR(191) NULL,
    ADD COLUMN `productWisePayoutRates` JSON NULL,
    ADD COLUMN `registeredAddressLine1` VARCHAR(191) NULL,
    ADD COLUMN `registeredAddressLine2` VARCHAR(191) NULL,
    ADD COLUMN `registeredCountry` VARCHAR(191) NULL,
    ADD COLUMN `registeredPinCode` VARCHAR(191) NULL,
    ADD COLUMN `roiProcessingFeeSharing` VARCHAR(191) NULL,
    ADD COLUMN `tdsRate` DOUBLE NULL,
    ADD COLUMN `tradeName` VARCHAR(191) NULL,
    ADD COLUMN `yearsInBusiness` INTEGER NULL;
